### Aula de métodos de regressão em Python

O pacote utilizado será o statsmodels, a documentação e exemplos práticos desse pacote podem ser encontrados no site https://www.statsmodels.org/stable/index.html

In [1]:
%pip install statsmodels

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: statsmodels in d:\anaconda3\lib\site-packages (0.14.4)
Requirement already satisfied: numpy<3,>=1.22.3 in d:\anaconda3\lib\site-packages (from statsmodels) (1.26.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in d:\anaconda3\lib\site-packages (from statsmodels) (1.15.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in d:\anaconda3\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in d:\anaconda3\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in d:\anaconda3\lib\site-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2023.3)
Requirement already satisfied: six>=1.5 in d:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

df = pd.read_stata('dados_estrategia_1.dta')
df = df[df.prazo >0]
df.head()

,data_inicio,data_nascimento_servidor,sexo,idAnon,idade,escolaridade,cor_origem_etnica,uf_resid,pais,uf_naturalidade,...,tempo_meses,sexo_num,raça,genero_raca,escolaridade_num,area_governo_num,estado_civil_num,nivel_inicial_num,ano_promoção,escolaridade_raca
0,2011-03-01,NaT,FEM,00002550ef8a6b844ed5b8ceb0427667d697feee20666d...,30.0,SUPERIOR,NAO INFORMADO,GO,,99,...,0.083447,1.0,2.0,4.0,3.0,3.0,3.0,0.0,NaN,0.0
1,2010-09-01,1960-04-08,MAS,00006f339e66296413d4759eaf93f87fbccec44afff009...,50.0,ENSINO MEDIO,NEGRA,MT,,99,...,0.790926,0.0,1.0,2.0,2.0,3.0,3.0,0.0,NaN,10.0
2,2000-03-01,1963-10-20,FEM,0000bc7a016e8ea23748a4c9f4d480fde83aeccc742028...,36.0,SUPERIOR,BRANCA,DF,,99,...,1.977884,1.0,0.0,1.0,3.0,0.0,3.0,0.0,NaN,3.0
3,2000-03-01,1975-01-05,MAS,0000d8015ea5abe17e132de2a9127008db506efa9e5b4b...,25.0,ENSINO MEDIO,BRANCA,SE,,99,...,1.977884,0.0,0.0,0.0,2.0,2.0,3.0,0.0,NaN,2.0
4,2012-03-01,1985-07-24,FEM,0000df8852065c774b5c262b57bbb649ec1af01fd4b8e5...,26.0,SUPERIOR,BRANCA,SC,,99,...,0.145919,1.0,0.0,1.0,3.0,3.0,3.0,0.0,NaN,3.0

In [ ]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

sf = sm.SurvfuncRight(df["prazo"], df["status"])
sf.summary().head()

          Surv prob  Surv prob SE  num at risk  num events
Time
0.000000   0.999992      0.000004       602713         5.0
0.246238   0.999935      0.000010       600144        34.0
0.248974   0.999883      0.000014       599371        31.0
0.251710   0.999548      0.000028       588272       197.0
0.495212   0.999508      0.000029       573730        23.0

In [ ]:
mod = smf.phreg("prazo ~ 0 + sexo_num + C(escolaridade_num) + C(area_governo_num) + C(estado_civil_num)", df, status=df["status"], ties="efron")
rslt = mod.fit()
print(rslt.summary())

d:\anaconda3\Lib\site-packages\statsmodels\duration\hazard_regression.py:425: UserWarning: PHReg formulas should not include any '0' or '1' terms
  warnings.warn("PHReg formulas should not include any '0' or '1' terms")

                                 Results: PHReg
=================================================================================
Model:                           PH Reg            Sample size:            600144
Dependent variable:              prazo             Num. events:            16564
Ties:                            Efron
---------------------------------------------------------------------------------
                            log HR log HR SE   HR      t     P>|t|  [0.025 0.975]
---------------------------------------------------------------------------------
C(escolaridade_num)[0.0]   -7.9822       nan 0.0003      nan    nan    nan    nan
C(escolaridade_num)[1.0]   -0.1833       nan 0.8325      nan    nan    nan    nan
C(escolaridade_num)[2.0]    0.5971       nan 1.8168      nan    nan    nan    nan
C(escolaridade_num)[3.0]    1.6640       nan 5.2803      nan    nan    nan    nan
C(escolaridade_num)[4.0]    0.5527       nan 1.7379      nan    nan    nan    nan
C(escolaridade_num)[5.0]    1.8310       nan 6.2401      nan    nan    nan    nan
C(escolaridade_num)[6.0]    1.4329       nan 4.1910      nan    nan    nan    nan
C(escolaridade_num)[7.0]    2.0881       nan 8.0697      nan    nan    nan    nan
C(area_governo_num)[T.1.0]  0.4332    0.0353 1.5421  12.2539 0.0000 1.4389 1.6527
C(area_governo_num)[T.2.0]  0.2385    0.0197 1.2694  12.1092 0.0000 1.2213 1.3193
C(area_governo_num)[T.3.0] -0.7427    0.0232 0.4758 -31.9773 0.0000 0.4547 0.4980
C(estado_civil_num)[T.1.0]  0.3219    0.0356 1.3797   9.0395 0.0000 1.2867 1.4794
C(estado_civil_num)[T.2.0]  0.0429    0.0657 1.0438   0.6526 0.5140 0.9177 1.1872
C(estado_civil_num)[T.3.0] -0.2866    0.0300 0.7508  -9.5385 0.0000 0.7079 0.7964
sexo_num                   -0.2293    0.0167 0.7951 -13.7519 0.0000 0.7696 0.8215
=================================================================================
Confidence intervals are for the hazard ratios

d:\anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
d:\anaconda3\Lib\site-packages\statsmodels\duration\hazard_regression.py:1423: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(np.diag(self.cov_params()))

In [15]:
import pandas as pd

df = pd.read_stata('logit_henrique.dta')
df.head()

,data_inicio,data_nascimento_servidor,sexo,idAnon,idade,escolaridade,cor_origem_etnica,uf_resid,pais,uf_naturalidade,...,tempo_meses,sexo_num,raça,genero_raca,escolaridade_num,area_governo_num,estado_civil_num,nivel_inicial_num,ano_promoção,escolaridade_raca
0,2010-09-01,1960-04-08,MAS,00006f339e66296413d4759eaf93f87fbccec44afff009...,50.0,ENSINO MEDIO,NEGRA,MT,,99,...,152.166672,0.0,1.0,2.0,2.0,3.0,3.0,0.0,NaN,10.0
1,2000-03-01,1963-10-20,FEM,0000bc7a016e8ea23748a4c9f4d480fde83aeccc742028...,36.0,SUPERIOR,BRANCA,DF,,99,...,152.166672,1.0,0.0,1.0,3.0,0.0,3.0,0.0,NaN,3.0
2,2000-03-01,1963-10-20,FEM,0000bc7a016e8ea23748a4c9f4d480fde83aeccc742028...,36.0,SUPERIOR,BRANCA,DF,,99,...,304.333344,1.0,0.0,1.0,3.0,0.0,3.0,0.0,NaN,3.0
3,2000-03-01,1963-10-20,FEM,0000bc7a016e8ea23748a4c9f4d480fde83aeccc742028...,36.0,SUPERIOR,BRANCA,DF,,99,...,456.500000,1.0,0.0,1.0,3.0,0.0,3.0,0.0,NaN,3.0
4,2000-03-01,1975-01-05,MAS,0000d8015ea5abe17e132de2a9127008db506efa9e5b4b...,25.0,ENSINO MEDIO,BRANCA,SE,,99,...,152.166672,0.0,0.0,0.0,2.0,2.0,3.0,0.0,NaN,2.0

In [19]:
mod = smf.logit("logit_10years ~ 0 + sexo_num + C(raça) + C(escolaridade_num) + C(area_governo_num) + C(estado_civil_num)", df)
rslt = mod.fit()
margins = rslt.get_margeff()
print(margins.summary())

Optimization terminated successfully.
         Current function value: 0.087290
         Iterations 9
        Logit Marginal Effects
=====================================
Dep. Variable:          logit_10years
Method:                          dydx
At:                           overall
==============================================================================================
                                dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
C(raça)[0.0]                  -0.0706      0.002    -37.363      0.000      -0.074      -0.067
C(raça)[1.0]                  -0.0696      0.002    -36.965      0.000      -0.073      -0.066
C(raça)[2.0]                  -0.0737      0.002    -37.722      0.000      -0.078      -0.070
C(escolaridade_num)[T.2.0]     0.0069      0.001      8.302      0.000       0.005       0.009
C(escolaridade_num)[T.3.0]     0.0181      0.001     22.671      0.000       0.017       0.020
C(escolaridade_num)[T.4.0]     0.0062      0.002      3.500      0.000       0.003       0.010
C(escolaridade_num)[T.5.0]     0.0168      0.002      9.289      0.000       0.013       0.020
C(escolaridade_num)[T.6.0]     0.0137      0.002      5.657      0.000       0.009       0.018
C(escolaridade_num)[T.7.0]     0.0352      0.002     15.458      0.000       0.031       0.040
C(area_governo_num)[T.1.0]     0.0024      0.001      2.411      0.016       0.000       0.004
C(area_governo_num)[T.2.0]     0.0002      0.000      0.476      0.634      -0.001       0.001
C(area_governo_num)[T.3.0]    -0.0175      0.001    -29.221      0.000      -0.019      -0.016
C(estado_civil_num)[T.1.0]    -0.0058      0.003     -2.025      0.043      -0.011      -0.000
C(estado_civil_num)[T.2.0]    -0.0080      0.008     -0.980      0.327      -0.024       0.008
C(estado_civil_num)[T.3.0]    -0.0075      0.002     -4.642      0.000      -0.011      -0.004
sexo_num                      -0.0014      0.000     -3.526      0.000      -0.002      -0.001
==============================================================================================

In [29]:
df = pd.read_csv('student-mat.csv', sep = ';')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [38]:
df = pd.get_dummies(df, drop_first = True, dtype=int)
df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,1,0,1,0,0,0,1,1,0,0
1,17,1,1,1,2,0,5,3,3,1,...,0,0,0,1,0,0,0,1,1,0
2,15,1,1,1,2,3,4,3,2,2,...,1,0,1,0,1,0,1,1,1,0
3,15,4,2,1,3,0,3,2,2,1,...,1,0,0,1,1,1,1,1,1,1
4,16,3,3,1,2,0,4,3,2,1,...,0,0,0,1,1,0,1,1,0,0

In [39]:
df.columns

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2',
       'G3', 'school_MS', 'sex_M', 'address_U', 'famsize_LE3', 'Pstatus_T',
       'Mjob_health', 'Mjob_other', 'Mjob_services', 'Mjob_teacher',
       'Fjob_health', 'Fjob_other', 'Fjob_services', 'Fjob_teacher',
       'reason_home', 'reason_other', 'reason_reputation', 'guardian_mother',
       'guardian_other', 'schoolsup_yes', 'famsup_yes', 'paid_yes',
       'activities_yes', 'nursery_yes', 'higher_yes', 'internet_yes',
       'romantic_yes'],
      dtype='object')

In [42]:
mod = smf.gls("G1 ~ C(age) + Medu + Fedu + traveltime + studytime + freetime + sex_M + Mjob_teacher + Fjob_teacher + internet_yes + famrel", df)
rslt = mod.fit()
print(rslt.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                     G1   R-squared:                       0.119
Model:                            GLS   Adj. R-squared:                  0.079
Method:                 Least Squares   F-statistic:                     2.987
Date:                Mon, 17 Nov 2025   Prob (F-statistic):           7.01e-05
Time:                        19:03:00   Log-Likelihood:                -1008.9
No. Observations:                 395   AIC:                             2054.
Df Residuals:                     377   BIC:                             2125.
Df Model:                          17
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        7.3066      1.271      5.749      0.000       4.808       9.806
C(age)[T.16]     0.1087      0.477      0.228      0.820      -0.829       1.046
C(age)[T.17]     0.1226      0.485      0.253      0.801      -0.831       1.076
C(age)[T.18]    -0.1656      0.504     -0.329      0.743      -1.157       0.826
C(age)[T.19]    -0.2152      0.754     -0.286      0.775      -1.697       1.267
C(age)[T.20]     2.8469      1.919      1.483      0.139      -0.927       6.621
C(age)[T.21]     0.5264      3.269      0.161      0.872      -5.901       6.954
C(age)[T.22]    -4.4526      3.243     -1.373      0.171     -10.830       1.925
Medu             0.3111      0.208      1.499      0.135      -0.097       0.719
Fedu             0.2261      0.198      1.143      0.254      -0.163       0.615
traveltime      -0.2409      0.239     -1.008      0.314      -0.711       0.229
studytime        0.7843      0.207      3.781      0.000       0.376       1.192
freetime        -0.0180      0.170     -0.106      0.916      -0.353       0.317
sex_M            0.9749      0.352      2.767      0.006       0.282       1.668
Mjob_teacher    -0.4201      0.522     -0.805      0.421      -1.447       0.606
Fjob_teacher     1.6809      0.668      2.515      0.012       0.367       2.995
internet_yes     0.3387      0.451      0.751      0.453      -0.548       1.226
famrel           0.0403      0.184      0.219      0.827      -0.322       0.402
==============================================================================
Omnibus:                        8.854   Durbin-Watson:                   2.031
Prob(Omnibus):                  0.012   Jarque-Bera (JB):                6.203
Skew:                           0.177   Prob(JB):                       0.0450
Kurtosis:                       2.498   Cond. No.                         145.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [2]:
import pandas as pd

df = pd.read_csv('heart_failure_clinical_records_dataset.csv')
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [3]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

sf = sm.SurvfuncRight(df["time"], df["DEATH_EVENT"])
sf.summary().head()

      Surv prob  Surv prob SE  num at risk  num events
Time
4      0.996656      0.003339          299         1.0
6      0.993311      0.004714          298         1.0
7      0.986622      0.006644          297         2.0
8      0.979933      0.008110          295         2.0
10     0.959866      0.011351          293         6.0

In [5]:
mod = smf.phreg("time ~ 0 + age + anaemia +creatinine_phosphokinase + diabetes + ejection_fraction + high_blood_pressure + platelets + serum_creatinine + serum_sodium + sex + smoking", df, status=df["DEATH_EVENT"], ties="efron")
rslt = mod.fit()
print(rslt.summary())

                                Results: PHReg
==============================================================================
Model:                           PH Reg            Sample size:            299
Dependent variable:              time              Num. events:            96
Ties:                            Efron
------------------------------------------------------------------------------
                          log HR log HR SE   HR      t    P>|t|  [0.025 0.975]
------------------------------------------------------------------------------
age                       0.0464    0.0093 1.0475  4.9773 0.0000 1.0285 1.0668
anaemia                   0.4601    0.2168 1.5843  2.1220 0.0338 1.0358 2.4233
creatinine_phosphokinase  0.0002    0.0001 1.0002  2.2255 0.0260 1.0000 1.0004
diabetes                  0.1399    0.2231 1.1501  0.6269 0.5307 0.7427 1.7811
ejection_fraction        -0.0489    0.0105 0.9522 -4.6719 0.0000 0.9329 0.9720
high_blood_pressure       0.4757    0.2162 1.6092  2.2005 0.0278 1.0534 2.4583
platelets                -0.0000    0.0000 1.0000 -0.4116 0.6806 1.0000 1.0000
serum_creatinine          0.3210    0.0702 1.3786  4.5751 0.0000 1.2014 1.5818
serum_sodium             -0.0442    0.0233 0.9568 -1.8993 0.0575 0.9141 1.0014
sex                      -0.2375    0.2516 0.7886 -0.9440 0.3452 0.4816 1.2913
smoking                   0.1289    0.2512 1.1376  0.5132 0.6078 0.6953 1.8614
==============================================================================
Confidence intervals are for the hazard ratios

d:\anaconda3\Lib\site-packages\statsmodels\duration\hazard_regression.py:425: UserWarning: PHReg formulas should not include any '0' or '1' terms
  warnings.warn("PHReg formulas should not include any '0' or '1' terms")