In [7]:
import pandas as pd

# df = pd.read_json("previc.json")
# df = pd.read_csv('consulta_cand_2024_BRASIL.csv', sep=';',encoding='latin1')
# df = pd.read_csv('consulta_cand_2024_BRASIL.csv', sep=';',encoding='latin1')
# df = pd.read_csv('sentencas_classificadas_corrupcao.csv')
df = pd.read_excel('votacao_candidato_munzona_2024_BRASIL.xlsx')

df

,ANO_ELEICAO,NR_TURNO,DT_ELEICAO,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_CANDIDATO,...,DS_GENERO,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,CD_SIT_TOT_TURNO
0,2024,1,04/05/2025,PE,24236,GOIANA,Prefeito,170002489059,11,MARCILIO REGIO SILVEIRA DA COSTA,...,MASCULINO,7,SUPERIOR INCOMPLETO,3,CASADO(A),1,BRANCA,257,EMPRESÁRIO,1
1,2024,1,04/05/2025,PE,24236,GOIANA,Prefeito,170002489139,70,LUIZ EDUARDO SOUSA DOS SANTOS,...,MASCULINO,6,ENSINO MÉDIO COMPLETO,3,CASADO(A),3,PARDA,278,VEREADOR,4
2,2024,1,06/04/2025,BA,38458,RUY BARBOSA,Prefeito,50002480346,15,ERIDAN MARTINS DE ARAÚJO DOURADO,...,FEMININO,7,SUPERIOR INCOMPLETO,3,CASADO(A),3,PARDA,923,APOSENTADO (EXCETO SERVIDOR PÚBLICO),1
3,2024,1,06/04/2025,BA,38458,RUY BARBOSA,Prefeito,50002480349,55,GEORGE LUIZ BRITO DE CARVALHO,...,MASCULINO,8,SUPERIOR COMPLETO,3,CASADO(A),3,PARDA,111,MÉDICO,4
4,2024,1,06/04/2025,MS,91847,PARANHOS,Prefeito,120002482460,45,HELIO RAMÃO ACOSTA,...,MASCULINO,8,SUPERIOR COMPLETO,3,CASADO(A),3,PARDA,230,PEDAGOGO,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15354,2024,2,27/10/2024,SP,71838,TAUBATÉ,Prefeito,250001928721,30,SERGIO LUIZ VICTOR JUNIOR,...,MASCULINO,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,125,ADMINISTRADOR,1
15355,2024,2,27/10/2024,TO,73440,PALMAS,Prefeito,270001957302,22,JANAD MARQUES DE FREITAS VALCARI,...,FEMININO,8,SUPERIOR COMPLETO,9,DIVORCIADO(A),2,PRETA,277,DEPUTADO,4
15356,2024,2,27/10/2024,TO,73440,PALMAS,Prefeito,270001957302,22,JANAD MARQUES DE FREITAS VALCARI,...,FEMININO,8,SUPERIOR COMPLETO,9,DIVORCIADO(A),2,PRETA,277,DEPUTADO,6
15357,2024,2,27/10/2024,TO,73440,PALMAS,Prefeito,270002318894,20,JOSÉ EDUARDO DE SIQUEIRA CAMPOS,...,MASCULINO,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,1
15358,2024,2,27/10/2024,TO,73440,PALMAS,Prefeito,270002318894,20,JOSÉ EDUARDO DE SIQUEIRA CAMPOS,...,MASCULINO,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,6

In [ ]:
%pip uninstall fitz
%pip install pymupdf easyocr

Collecting pypdf
  Downloading pypdf-6.1.1-py3-none-any.whl.metadata (7.1 kB)
Downloading pypdf-6.1.1-py3-none-any.whl (323 kB)
Installing collected packages: pypdf
Successfully installed pypdf-6.1.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pymupdf as fitz
import easyocr

pdffile = "ocr_text.pdf"
doc = fitz.open(pdffile)
zoom = 4
mat = fitz.Matrix(zoom, zoom)
count = 0
# Count variable is to get the number of pages in the pdf
for p in doc:
    count += 1
for i in range(count):
    val = f"image_{i+1}.png"
    page = doc.load_page(i)
    pix = page.get_pixmap(matrix=mat)
    pix.save(val)
doc.close()

reader = easyocr.Reader(['pt'])
result = reader.readtext("image_1.png", detail=0)
result

Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
c:\Users\henri\miniconda3\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

['Presidencialismo e',
 'Governo de Coalizão',
 'Fernando Limongi',
 'De uns tempos para cá, referir-se ao sistema político brasileiro',
 'nomeando-o como presidencialismo de coalizão se tornou comum',
 'A adjetivação que passou a acompanhar nosso presidencialismo',
 'deixa subentendido que este tem algo de peculiar; de especial:',
 'Não praticaríamos um presidencialismo qualquer; vulgar;  Teríamos',
 'um',
 'regime com características próprias. Para 0 bem ou para 0 mal,',
 '0',
 'presidencialismo brasileiro funcionaria dessa forma particular;',
 'como um presidencialismo de coalizão .',
 'E esse modo peculiar de operar do sistema político é invocado',
 'tanto em tempos de calmaria quanto de turbulência. Se 0 cenário é',
 'de trangüilidade',
 'e',
 '0 governo tem sucesso em',
 'suas iniciativas, 0',
 'presidencialismo de coalizão é convocado para dar conta do que se',
 'passa. Em momentos de crise, recorre-se',
 'a ele para explicar os',
 'acontecimentos pouco abonadores que se lê nas páginas dos jor-',
 'nais elou dificuldades enfrentadas pelo governo para aprovar esta',
 'ou aquela medida.',
 'A entrada em voga do termo, seu uso generalizado no interior da',
 'literatura acadêmica',
 'e entre jornalistas, é relativamente recente, le',
 'vando-nos a concluir que esse formato peculiar de operar teria to-',
 'mado corpo há pouco',
 'Uma nova denominação que se prestaria a',
 'uma nova',
 'realidade; ou mais precisamente; para dar conta de uma',
 'mutação ocorrida nos últimos anos_',
 'Não é tão claro, no entanto; 0 que está por detrás dessa conver -',
 'gência terminológica. 0 que afinal seria',
 'um',
 'presidencialismo de',
 'coalizão? Qual sua forma peculiar de',
 'operação? Os dois termos',
 'que',
 'compõem a expressão, presidencialismo',
 'e',
 'coalizão, são bem',
 'conhecidos e de uso generalizado. Sabemos',
 'ou deveríamos saber',
 'que é um sistema de governo presidencialista. Sabemos',
 'ou',
 'também deveríamos saber',
 'como operam os governos basea-',
 'dos',
 'em coalizões partidárias.',
 'Não há nada de especial em',
 'um',
 'sistema presidencialista e',
 'em governos mantidos por coalizões',
 'partidárias. Mas; então; cabe se indagar por que a junção dos ter-',
 'mos seria capaz de nomear algo novo?',
 'A',
 'primeira parte deste artigo é dedicada a investigar as razões',
 'que poderiam explicar esta aspiração à originalidade, isto é',
 'às',
 'possíveis especificidades do sistema político brasileiro que justifi-',
 'cariam tomá-lo como um novo tipo de regime; como um presiden-',
 'cialismo de coalizão com direito',
 'a',
 'e',
 'itálico. A segunda parte',
 'trata do funcionamento do sistema político brasileiro; de sua estru-',
 'tura, procurando',
 'mostrar',
 'como',
 '0',
 'sistema presidencial brasileiro',
 'grifo']

In [19]:
from PyPDF2 import PdfReader

# Specify the path to your PDF file
pdf_path = "normal_text.pdf"

try:
    # Create a PdfReader object
    reader = PdfReader(pdf_path)

    # Get the total number of pages
    num_pages = len(reader.pages)
    print(f"Number of pages in the PDF: {num_pages}")

    # Extract text from a specific page (e.g., the first page)
    page = reader.pages[0]  # Access the first page (index 0)
    text = page.extract_text()
    print("\nText from the first page:")
    print(text)

    # You can loop through all pages to extract all text
    all_text = ""
    for page_num in range(num_pages):
        page = reader.pages[page_num]
        all_text += page.extract_text() + "\n"

    print("\nFull text from the PDF:")
    print(all_text)

except FileNotFoundError:
    print(f"Error: The file '{pdf_path}' was not found.")
except Exception as e:
    print(f"An error occurred: {e}")

Number of pages in the PDF: 33

Text from the first page:



(2016) 10 (2 )                                           e000 4 – 1/34


Unboxing the Active Role of the Legislative Power in
Brazil*

Andréa Marcondes de Freitas
Universidade Estadual de Campinas, Brazil

The main purpose of this article is to show the relevance
of the legislative branch participation in formatting bills
originating in the executive. It shows that a strong executive is not
necessarily accompanied by a weak legislature. By analyzing the
chan ges the legislative made to executive bills through substitute
bills and amendments to the legislation, the study shows that the
legislative branch actively participates in drafting policies. By such
means, the legislative branch is responsible for nearly 40 percent
of the content of the laws promulgated in Brazil. Even when the
executive takes steps aiming at controlling the legislative agenda,
such as provisional decrees or urgency requests, the rates of
legislative change do not decrease. As a result, in  spite of the
president institutional resources to place its own bills on the
agenda, the legislative branch do discuss, analyze and modify the
proposals advanced by the executive. An active instead of a
passive legislative power emerges from the data show n in this
article.
Keywords:  Executive; legislative branch; presidential
success; lawmaking.

______________________________________________________________________

 *     http://dx.doi.org/10.1590/1981 -38212016000200004
For data replication, see bpsr.org.br/files/archives/Dataset_Freitas


Full text from the PDF:



(2016) 10 (2 )                                           e000 4 – 1/34


Unboxing the Active Role of the Legislative Power in
Brazil*

Andréa Marcondes de Freitas
Universidade Estadual de Campinas, Brazil

The main purpose of this article is to show the relevance
of the legislative branch participation in formatting bills
originating in the executive. It shows that a strong executive is not
necessarily accompanied by a weak legislature. By analyzing the
chan ges the legislative made to executive bills through substitute
bills and amendments to the legislation, the study shows that the
legislative branch actively participates in drafting policies. By such
means, the legislative branch is responsible for nearly 40 percent
of the content of the laws promulgated in Brazil. Even when the
executive takes steps aiming at controlling the legislative agenda,
such as provisional decrees or urgency requests, the rates of
legislative change do not decrease. As a result, in  spite of the
president institutional resources to place its own bills on the
agenda, the legislative branch do discuss, analyze and modify the
proposals advanced by the executive. An active instead of a
passive legislative power emerges from the data show n in this
article.
Keywords:  Executive; legislative branch; presidential
success; lawmaking.

______________________________________________________________________

 *     http://dx.doi.org/10.1590/1981 -38212016000200004
For data replication, see bpsr.org.br/files/archives/Dataset_Freitas

Unboxing the Active Role of the Legislative
Power in Brazil
(2016) 10 (2 )                                           e000 4 – 2/34

atin American political systems are recognized as having presidents
with broad legislative powers (SANTOS, PÉREZ -LIÑÁN  and GARCIA
MONTEIRO, 2014). This feature has alerted political scientists to possible
deficiencies regarding the legislators ' ability to fully exercise their role.
Legislatures in these countries are usually defined as weak, or as mere "rubber
stamps " of the presidential agenda (COX and MORGENSTERN, 2001; O 'DONNELL,
1994).
Brazil is a notable example of a presidency with strong legislative powers.
The president approves most of the proposals sent to the legislature – with high
success rates – and most of the l aws come from bills initiated by the executive –
with high rates of dominance (FIGUEIREDO and LIMONGI, 1999). The explanations
for this success and dominance are based on presidential powers – powers over
agenda and discretionary control of appointments and budget (AMORIM NETO,
2000; AMORIM NETO, COX, and MCCUBBINS, 2003; FIGUEIREDO and LIMONGI,
1999, 2008; MELO and PEREIRA, 2013; PEREIRA and MUELLER, 2002). In this
context, in which the explanations for governability focus exclusively on the ability
of the executive to promote it, doubts emerge as to the ability of the legislative
branch to fully exercise its functions. This is particularly true when dealing with its
main function, which is to assess, debate and produce laws.
However, what is the real ability of the legislature to affect the content of
policies in an unbalanced context between the branches? Is the ability of the
legislative branch to deliberate and modify executive proposals affected by the
legislative powers of the president? These questions guide this article. It will be
shown that the extensive executive authority is not an imped iment to the
legislature action, to the extent that none of the resources available to the
executive are capable of inhibiting the active participation of the legislative branch
in the process of making laws. To demonstrate this point, I will analyze
amend ments and substitute bills made by Congress to ordinary bills (projetos de
lei ordinária  – PL), provisional decrees (medidas provisórias – MPV) and
complementary bills (projetos de lei complementar – PLP) sent by the executive
during the governments of Fer nando Henrique Cardoso and Luiz Inácio Lula da L
Andréa Marcondes de Freitas
(2016) 10 (2 )                                           e000 4 – 3/34
Silva, which were partially or totally vetoed1. Therefore, what is intended to show
is that the high rates of success and executive predominance do not explain the
high degree of participation of the legislati ve branch in the legal output of the
country.
This article is divided into five parts. In the first part, brief considerations
are made on the balance of power between the executive and legislative branches,
attempting to show that a strong executive does not necessarily imply a weak
legislature. The second part presents the methodology used to evaluate the
modifications made by the legislature. The third part presents the impact of the
modifications made by legislative amendments and substitute bills in th e laws. The
fourth part shows that the powers of agenda of the executive and party leaders do
not affect legislature ability to change executive proposals. Lastly, final
considerations are given.

Strong executive, weak legislature?
The presidency in Brazi l has broad legislative powers, it is able to issue
provisional decrees (medidas provisórias) which have the force of law from the
moment of publication and can request urgency for the bills that it proposed,
significantly limiting the time for evaluating its proposals by the legislature (45
days in each legislative house). The presidency also has exclusive initiative over
budgetary and administrative matters, that is, it has agenda powers. The president
also has negative powers and is able to partially or totally veto bills ratified by the
legislative power. Furthermore, Brazilian presidents have a wide range of
resources at their disposal, discretionary control over the budget2 and over
appointments.
______________________________________________________________________

1 Matters that had been vetoed because they make explicit a possible conflict between the
executive and legislative branches were chosen. It is important to highlight that, among
these matters, there are central themes to Brazilian politics in recent years, such as: bills
addressing minimum wage, the Law of Fiscal Responsibility, income tax and other taxes,
bills that reorganize the careers of public servants, the ProUNI bill, and Minha Casa, Minha
Vida , (My House, My Life), among others. For a complete list,  see Apendix A published
online (see http://bpsr.org.br/files/archives/Dataset_Freitas).
2 This power was reduced since the introduction of the imposed budget, which requires
the president to implement the parliamentary amendments to the budget. The recent
change, introduced for the 2014 budget through the budgetary law (Law n º 12,919),
confirmed by Constitutional Amendment n º  86, still does not allow us to veri y its effects.
Unboxing the Active Role of the Legislative
Power in Brazil
(2016) 10 (2 )                                           e000 4 – 4/34
This broad set of presidential powers is associated with  high rates of
success and the power this branch has in the approval of its agenda. However, it
raises important considerations about the ability of the legislature to fully exercise
its role. The discussion about the medidas provisórias  (provisional decrees – MPVs)
exemplifies this issue. Considered by Amorim Neto and Tafner (2002 , p. 28) as an
anti -majority instrument, the MPVs are always mentioned when it comes to the
low capacity of the legislative branch facing the powers of the pres ident. It is not
without reason that a large part of the debate around this topic is dedicated to
understanding whether or not the legislative branch abdicates its authority to
legislate in favor of the executive (AMORIM NETO and TAFNER, 2002;
FIGUEIREDO and LIMONGI, 1997). The conclusions that the authors reach are
diverse, and substantives as usurpation, abdication and delegation are used to
refer to the modus operandi  in the relationship between the executive and
legislative branches.
It is common that, referring to governability, the focus falls on the means
used by the executive to annul the private interests that would guide the action of
the legislature. If taken to the extreme, the result would be that the powers of the
president would take away any possibility of legislative action. Even when the
explanation has partisan grounds, it tends to be concentrated on how the
centralization of the legislative process, in the hands of the party leaders would
reduce the fragmented and personal incentives comin g from the electoral system.
Thus, even though governability is recognized as a fact today, it seems to be
assured in spite of the legislative branch by means of its neutralization.
Nevertheless, are strong presidents necessarily accompanied by weak
legisl atures? How, and to what extent, do presidential powers reduce the ability of
the legislative branch? By centering on the success and dominance of the executive,
the discussions around the issue of governability leave aside an important aspect
of the funct ioning of the system, which is the ability of the legislature to fully
evaluate the proposals of the executive. It has been deducted that the strengths of
the powers are correlated. Thus, if the executive is powerful, the legislature is
Andréa Marcondes de Freitas
(2016) 10 (2 )                                           e000 4 – 5/34
weak, and vice -vers a. The same may be said of success: if the executive is
successful, this means that the legislature is not3.
However, this is done without proper consideration of how the
presidential powers in fact minimize the ability of the legislative branch. Do the
three types of presidential power – i.e., power of veto, control of resources and
powers of agenda – affect the decision -making ability of the legislative branch?
The resources at the disposal of the executive, in the Brazilian case,
discretionary control of  appointments and budget, change the incentives for the
legislators, facilitating the process of coordination in order to make it easier for the
executive to build a systematic base of support in the legislative. This encourages,
for example, the formation  of coalitions that support the executive. However, the
presence of incentives does not imply that some legislators cannot choose the
opposition. For certain parties, the incentives to remain in the opposition will be
greater than those provided by the res ources of the executive. On the other hand,
even though this is an important instrument for the process of negotiation, these
resources do not hinder the evaluation and modification of bills coming from the
executive. At most, they limit  with whom this bra nch will negotiate in forming its
agenda (FREITAS, 2013).
Veto power, insofar as it leads the legislature to anticipate the preferences
of the executive, fosters negotiation between the powers, particularly where the
partial veto is permitted. However, her e it should also be considered that unilateral
action is not possible; or, if it is, only the legislature can pass legislation without
the consent of the executive, but this would require the formation of large
majorities4. The legislators can anticipate t hat a given modification will be vetoed,
but they cannot assume that they will simply ratify a proposal much different from
______________________________________________________________________

3 Obviously, it must be considered that the resources of a State are limited, and  a large part
of the work of the representatives is precisely to decide how these resources will be
distributed. Furthermore, if the total amount of resources is limited, then in order to make
new policies it must be determined which policies will not be i mplemented. The argument
that I seek to develop does not harm this logic. The point is that, given that none of the
powers can make policy unilaterally, the legislative and the executive negotiate to arrive at
a minimum consensus that permits some policy i nstead of no policy.
4 Also, the legislative bills and the proposed changes within this branch are subject to
presidential veto. Unless they have raised a sufficient majority to overturn the presidential
veto, the legislative branch has no way to act unila terally.
Unboxing the Active Role of the Legislative
Power in Brazil
(2016) 10 (2 )                                           e000 4 – 6/34
their preferences. It is more likely that, in the process of anticipation, both powers
will moderate their proposals in order to mak e them viable.
The legislative powers of the president, on the other hand, interfere in the
legislative agenda. Agenda, in political science, is always considered to have a
double meaning – timing and content (FIGUEIREDO and LIMONGI, 1999).
However, the po wers of the president are not able to define the content itself, but
they can define the topic. Powers of agenda, as provisional decrees or of
constitutional urgency, can determine when a bill will be voted on, and they are
able to determine what topic the  legislature will debate, even if the legislature does
not want the topic to be debated. Nevertheless, different from what is normally
assumed, powers of agenda do not imply that the executive has control of the
content to the extent that the executive is unable either to prevent changes thereto
or to avoid rejection of the bills. Powers of agenda, like the other powers of the
Executive, change the incentives. Provisional decrees, for example, can change the
incentives for the legislators to the extent that  they may provide cover for them to
support the executive (FIGUEIREDO and LIMONGI, 1999; HUBER, 1996).
Provisional decrees also create a legal problem when they are altered or rejected.
The legislature is responsible to solve this kind of problem,  which r educes the
incentives for legislative action. However, these decrees are still neither rejection -
nor change -proof.
In theory, none of these mechanisms available to the executive reduce the
ability of the legislative branch to change or reject what is bein g proposed. As
Immergut (1996)  reminds us, instituti ons provide the context in which politicians
will act. They define incentives and shape strategies, but do not determine results.
None of the powers of the president permits this branch unilateral action
because the legislature approval is always necessary . The opposite is also true: the
legislature is not able to approve bills too far from the preference of the executive,
unless they are able to amass a vast majority.
The presidential powers do not imply any weakening of the legislative
branch. Strong presidents do not imply weak legislatures because the powers
given to one or another branch are not complementary. The same may be said
about success: the president 's success does not imply failure of the legislature.
Even though presidential systems are c haracterized by independence between
Andréa Marcondes de Freitas
(2016) 10 (2 )                                           e000 4 – 7/34
branches, what guarantees the mutual oversight capacity of the branches is just a
high degree of overlap of their functions, which demands a high degree of
coordination. The powers of the president, together with the ce ntralization of the
legislature around the party leaders, promote the capacity for coordination
between the branches, as Figueiredo and Limongi  (1999 ) point out, diminishing
the fragmenting effects of the electoral arena. Yet, this does not imply weakening  of
the legislative branch to the extent that president powers are not able to hinder
the action of the legislators. Institutions provide incentives and regulate the
strategies available to the actors, but do not define the results.
However, what does alte ration of the executive 's bill mean, from the point
of view of presidential success? Bonvecchi and Zelaznik (2012) , dealing with
presidential success, claim that the analysis in search of evaluating success by
counting both the bills introduced and signed into law are insufficient because they
do not take into account to what extent  the bills are changed. Barrett and
Eshbaugh -Soha (2007) and Eshbaugh -Soha (2010)  take a similar path and show
that success may be better understood when the content proposed by the
executive that remains after passing through the legislature is examined. Martin
and Vanberg (2011) , looking at parliamentary countries, point out that
modifications to executive bills are consequences of the negotiations inside the
coalition. For the latter authors, the legislature would be a privileged arena for the
members of the coalition to control each other, avoiding the pitfalls imposed by the
delegation.
Stepan (1999)  and Ames (2003) , looking at the Brazilian case and taking
the l aw of anticipation of reactions as their premise, claim that the success of the
president in Brazil is overestimated primarily because the executive branch would
not send bills that would probably be rejected. Second, because bills sent are so
heavily alte red that they would lose their original features. From this point of view,
the changes would be unsuccessful for the executive. However, if this were the
case, why would the president not veto such changes?
The law of anticipation of reactions states that the president will
anticipate negative reactions to the bills, possibly not sending a bill to the
legislature in anticipation of its rejection. The same may be said of legislators about
changing executive bills; anticipating that the changes will be vetoed , the
Unboxing the Active Role of the Legislative
Power in Brazil
(2016) 10 (2 )                                           e000 4 – 8/34
legislators may prefer not to make them. What the authors do not consider is that
the legislators and/or the president may insist on a bill that will be rejected in
order to place the blame for inaction on the other branch. They also do not
consider that policies may be used to force a negotiation. Thus, the president may
send a bill to the legislature, radicalizing their preferences, in order to leave room
for negotiation. Finally, it must be considered that the anticipation may fail, or that
the con text may change and the preferences that seemed evident may change
during the process (DINIZ, 2005; LIMONGI, 2006).
The fact is that if the anticipation were perfect, the executive would never

In [ ]:
%pip install xlrd

Requirement already satisfied: pandas in c:\users\henri\miniconda3\lib\site-packages (2.3.0)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\henri\miniconda3\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\henri\miniconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\henri\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\henri\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\henri\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [17]:
import os
import pandas as pd

name_report = 'titanic3.xls'
df = pd.read_excel(name_report)
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [21]:
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [14]:
df.dropna(subset=['age']).isnull().sum()

pclass         0
survived       0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           1
cabin        774
embarked       2
boat         629
body         926
home.dest    361
dtype: int64

In [18]:
data = df.drop(columns = ['name','home.dest','boat','body','cabin','ticket'])
data.head()

   pclass  survived     sex      age  sibsp  parch      fare embarked
0       1         1  female  29.0000      0      0  211.3375        S
1       1         1    male   0.9167      1      2  151.5500        S
2       1         0  female   2.0000      1      2  151.5500        S
3       1         0    male  30.0000      1      2  151.5500        S
4       1         0  female  25.0000      1      2  151.5500        S

In [20]:
data = pd.get_dummies(data, drop_first = True, dtype=int)
data.head()
# data.isnull().sum()

,pclass,survived,age,sibsp,parch,fare,sex_male,embarked_Q,embarked_S
0,1,1,29.0000,0,0,211.3375,0,0,1
1,1,1,0.9167,1,2,151.5500,1,0,1
2,1,0,2.0000,1,2,151.5500,0,0,1
3,1,0,30.0000,1,2,151.5500,1,0,1
4,1,0,25.0000,1,2,151.5500,0,0,1

In [ ]:
data.to_excel('titanic_limpo.xlsx', index=False)
# data.to_csv('titanic_limpo.csv', index=False)
# data.to_json('titanic_limpo.json', index=False)