In [2]:
import pandas as pd

arquivos = ['dados_saude_1.csv', 'dados_saude_2.csv']
df = pd.DataFrame()
for arquivo in arquivos:
    df = pd.concat([df, pd.read_csv(arquivo)])
df.reset_index(drop=True, inplace=True)
df.head()

,numero_cnj,classe,assunto,magistrado,comarca,foro,vara,data_disponibilizacao,decisao
0,1014984-85.2025.8.26.0554,Procedimento Comum Cível,Tratamento médico-hospitalar,Alberto Gentil de Almeida Pedroso,Santo André,Foro de Santo André,8ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t1014984-...
1,1024257-39.2025.8.26.0053,Procedimento do Juizado Especial da Fazenda Pú...,Fornecimento de medicamentos,Alexandra Fuchs de Araujo,SÃO PAULO,Foro Central - Fazenda Pública/Acidentes,3ª Vara do Juizado Especial da Fazenda Pública...,08/09/2025,DECISÃO\r\n\r\nProcesso Digital nº:\t1024257-3...
2,0004884-06.2025.8.26.0161,Cumprimento Provisório de Sentença,Tratamento médico-hospitalar,RODRIGO SOUSA DAS GRACAS,Diadema,Foro de Diadema,3ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital:\t0004884-06....
3,0000017-17.2025.8.26.0210,Requisição de Pequeno Valor,Fornecimento de medicamentos,LUCAS DUCATTI MARQUEZ DE ANDRADE,Guaíra,Foro de Guaíra,1ª Vara,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t0000017-...
4,1016320-41.2024.8.26.0011,Procedimento Comum Cível,Tratamento médico-hospitalar,PAULO HENRIQUE RIBEIRO GARCIA,SÃO PAULO,Foro Regional XI - Pinheiros,1ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nCONCLUSÃO\r\nEm 05 de setembro...

In [9]:
df['ano'] = df.data_disponibilizacao.str[-4:]
df.head()

,numero_cnj,classe,assunto,magistrado,comarca,foro,vara,data_disponibilizacao,decisao,ano
0,1014984-85.2025.8.26.0554,Procedimento Comum Cível,Tratamento médico-hospitalar,Alberto Gentil de Almeida Pedroso,Santo André,Foro de Santo André,8ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t1014984-...,2025
1,1024257-39.2025.8.26.0053,Procedimento do Juizado Especial da Fazenda Pú...,Fornecimento de medicamentos,Alexandra Fuchs de Araujo,SÃO PAULO,Foro Central - Fazenda Pública/Acidentes,3ª Vara do Juizado Especial da Fazenda Pública...,08/09/2025,DECISÃO\r\n\r\nProcesso Digital nº:\t1024257-3...,2025
2,0004884-06.2025.8.26.0161,Cumprimento Provisório de Sentença,Tratamento médico-hospitalar,RODRIGO SOUSA DAS GRACAS,Diadema,Foro de Diadema,3ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital:\t0004884-06....,2025
3,0000017-17.2025.8.26.0210,Requisição de Pequeno Valor,Fornecimento de medicamentos,LUCAS DUCATTI MARQUEZ DE ANDRADE,Guaíra,Foro de Guaíra,1ª Vara,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t0000017-...,2025
4,1016320-41.2024.8.26.0011,Procedimento Comum Cível,Tratamento médico-hospitalar,PAULO HENRIQUE RIBEIRO GARCIA,SÃO PAULO,Foro Regional XI - Pinheiros,1ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nCONCLUSÃO\r\nEm 05 de setembro...,2025

In [ ]:
df.groupby(['ano','comarca']).magistrado.nunique().reset_index()
# total_magistrados = df.groupby(['ano','comarca']).magistrado.nunique().reset_index()

       ano           comarca  magistrado
0     2010         SÃO PAULO           2
1     2011         SÃO PAULO           1
2     2012         SÃO PAULO           1
3     2013           Dracena           1
4     2013    Embu das Artes           1
...    ...               ...         ...
2001  2025         Viradouro           3
2002  2025        Votorantim           4
2003  2025       Votuporanga           7
2004  2025   Várzea Paulista           2
2005  2025  Águas de Lindóia           2

[2006 rows x 3 columns]

In [ ]:
df.groupby(['ano','comarca']).numero_cnj.count().reset_index()
# total_processos = df.groupby(['ano','comarca']).numero_cnj.count().reset_index()

       ano           comarca  numero_cnj
0     2010         SÃO PAULO           2
1     2011         SÃO PAULO           1
2     2012         SÃO PAULO           1
3     2013           Dracena           1
4     2013    Embu das Artes           1
...    ...               ...         ...
2001  2025         Viradouro          47
2002  2025        Votorantim          45
2003  2025       Votuporanga          73
2004  2025   Várzea Paulista          24
2005  2025  Águas de Lindóia          27

[2006 rows x 3 columns]

In [ ]:
total_magistrados = df.groupby(['ano','comarca']).magistrado.nunique().reset_index()
total_magistrados['key'] = total_magistrados.ano + '_' + total_magistrados.comarca
total_magistrados

       ano         comarca  magistrado                  key
0     2010       SÃO PAULO           2       2010_SÃO PAULO
1     2011       SÃO PAULO           1       2011_SÃO PAULO
2     2012       SÃO PAULO           1       2012_SÃO PAULO
3     2013         Dracena           1         2013_Dracena
4     2013  Embu das Artes           1  2013_Embu das Artes
...    ...             ...         ...                  ...
1991  2025   Tupi Paulista           1   2025_Tupi Paulista
1992  2025            Tupã           5            2025_Tupã
1993  2025         Ubatuba           4         2025_Ubatuba
1994  2025          Urupês           1          2025_Urupês
1995  2025          Urânia           3          2025_Urânia

[1996 rows x 4 columns]

In [ ]:
total_processos = df.groupby(['ano','comarca']).numero_cnj.count().reset_index()
total_processos['key'] = total_processos.ano.astype(str) + '_' + total_processos.comarca
total_processos

       ano         comarca  numero_cnj                  key
0     2010       SÃO PAULO           2       2010_SÃO PAULO
1     2011       SÃO PAULO           1       2011_SÃO PAULO
2     2012       SÃO PAULO           1       2012_SÃO PAULO
3     2013         Dracena           1         2013_Dracena
4     2013  Embu das Artes           1  2013_Embu das Artes
...    ...             ...         ...                  ...
1991  2025   Tupi Paulista           8   2025_Tupi Paulista
1992  2025            Tupã          74            2025_Tupã
1993  2025         Ubatuba          43         2025_Ubatuba
1994  2025          Urupês          20          2025_Urupês
1995  2025          Urânia          19          2025_Urânia

[1996 rows x 4 columns]

In [55]:
pd.merge(total_processos, total_magistrados, on='key', how='inner')
# pd.merge(total_processos, total_magistrados, on='key', how='outer')
# pd.merge(total_processos, total_magistrados, on='key', how='left')
# pd.merge(total_processos, total_magistrados, on='key', how='right')

,ano_x,comarca_x,numero_cnj,key,ano_y,comarca_y,magistrado
0,2010,SÃO PAULO,2,2010_SÃO PAULO,2010,SÃO PAULO,2
1,2011,SÃO PAULO,1,2011_SÃO PAULO,2011,SÃO PAULO,1
2,2012,SÃO PAULO,1,2012_SÃO PAULO,2012,SÃO PAULO,1
3,2013,Dracena,1,2013_Dracena,2013,Dracena,1
4,2013,Embu das Artes,1,2013_Embu das Artes,2013,Embu das Artes,1
...,...,...,...,...,...,...,...
2001,2025,Viradouro,47,2025_Viradouro,2025,Viradouro,3
2002,2025,Votorantim,45,2025_Votorantim,2025,Votorantim,4
2003,2025,Votuporanga,73,2025_Votuporanga,2025,Votuporanga,7
2004,2025,Várzea Paulista,24,2025_Várzea Paulista,2025,Várzea Paulista,2
2005,2025,Águas de Lindóia,27,2025_Águas de Lindóia,2025,Águas de Lindóia,2

In [56]:
dados_desc = pd.merge(total_processos, total_magistrados, on='key', how='inner')
dados_desc.drop(columns=['ano_y','ano_x','comarca_x','comarca_y'], inplace=True)
dados_desc

      numero_cnj                    key  magistrado
0              2         2010_SÃO PAULO           2
1              1         2011_SÃO PAULO           1
2              1         2012_SÃO PAULO           1
3              1           2013_Dracena           1
4              1    2013_Embu das Artes           1
...          ...                    ...         ...
2001          47         2025_Viradouro           3
2002          45        2025_Votorantim           4
2003          73       2025_Votuporanga           7
2004          24   2025_Várzea Paulista           2
2005          27  2025_Águas de Lindóia           2

[2006 rows x 3 columns]

In [57]:
df['key'] = df.ano.astype(str) + '_' + df.comarca
df.head()

,numero_cnj,classe,assunto,magistrado,comarca,foro,vara,data_disponibilizacao,decisao,ano,key
0,1014984-85.2025.8.26.0554,Procedimento Comum Cível,Tratamento médico-hospitalar,Alberto Gentil de Almeida Pedroso,Santo André,Foro de Santo André,8ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t1014984-...,2025,2025_Santo André
1,1024257-39.2025.8.26.0053,Procedimento do Juizado Especial da Fazenda Pú...,Fornecimento de medicamentos,Alexandra Fuchs de Araujo,SÃO PAULO,Foro Central - Fazenda Pública/Acidentes,3ª Vara do Juizado Especial da Fazenda Pública...,08/09/2025,DECISÃO\r\n\r\nProcesso Digital nº:\t1024257-3...,2025,2025_SÃO PAULO
2,0004884-06.2025.8.26.0161,Cumprimento Provisório de Sentença,Tratamento médico-hospitalar,RODRIGO SOUSA DAS GRACAS,Diadema,Foro de Diadema,3ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital:\t0004884-06....,2025,2025_Diadema
3,0000017-17.2025.8.26.0210,Requisição de Pequeno Valor,Fornecimento de medicamentos,LUCAS DUCATTI MARQUEZ DE ANDRADE,Guaíra,Foro de Guaíra,1ª Vara,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t0000017-...,2025,2025_Guaíra
4,1016320-41.2024.8.26.0011,Procedimento Comum Cível,Tratamento médico-hospitalar,PAULO HENRIQUE RIBEIRO GARCIA,SÃO PAULO,Foro Regional XI - Pinheiros,1ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nCONCLUSÃO\r\nEm 05 de setembro...,2025,2025_SÃO PAULO

In [59]:
pd.merge(df, dados_desc, on='key', how='left').head()

,numero_cnj_x,classe,assunto,magistrado_x,comarca,foro,vara,data_disponibilizacao,decisao,ano,key,numero_cnj_y,magistrado_y
0,1014984-85.2025.8.26.0554,Procedimento Comum Cível,Tratamento médico-hospitalar,Alberto Gentil de Almeida Pedroso,Santo André,Foro de Santo André,8ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t1014984-...,2025,2025_Santo André,379,18
1,1024257-39.2025.8.26.0053,Procedimento do Juizado Especial da Fazenda Pú...,Fornecimento de medicamentos,Alexandra Fuchs de Araujo,SÃO PAULO,Foro Central - Fazenda Pública/Acidentes,3ª Vara do Juizado Especial da Fazenda Pública...,08/09/2025,DECISÃO\r\n\r\nProcesso Digital nº:\t1024257-3...,2025,2025_SÃO PAULO,6555,413
2,0004884-06.2025.8.26.0161,Cumprimento Provisório de Sentença,Tratamento médico-hospitalar,RODRIGO SOUSA DAS GRACAS,Diadema,Foro de Diadema,3ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital:\t0004884-06....,2025,2025_Diadema,119,10
3,0000017-17.2025.8.26.0210,Requisição de Pequeno Valor,Fornecimento de medicamentos,LUCAS DUCATTI MARQUEZ DE ANDRADE,Guaíra,Foro de Guaíra,1ª Vara,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t0000017-...,2025,2025_Guaíra,34,4
4,1016320-41.2024.8.26.0011,Procedimento Comum Cível,Tratamento médico-hospitalar,PAULO HENRIQUE RIBEIRO GARCIA,SÃO PAULO,Foro Regional XI - Pinheiros,1ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nCONCLUSÃO\r\nEm 05 de setembro...,2025,2025_SÃO PAULO,6555,413

In [1]:
%pip install langchain_text_splitters langchain_experimental langchain_huggingface

Requirement already satisfied: langchain_text_splitters in c:\users\henri\miniconda3\lib\site-packages (0.3.8)
Requirement already satisfied: langchain_experimental in c:\users\henri\miniconda3\lib\site-packages (0.3.4)
Requirement already satisfied: langchain_huggingface in c:\users\henri\miniconda3\lib\site-packages (0.3.1)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.51 in c:\users\henri\miniconda3\lib\site-packages (from langchain_text_splitters) (0.3.76)
Requirement already satisfied: langsmith>=0.3.45 in c:\users\henri\miniconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (0.3.45)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\henri\miniconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (9.1.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\henri\miniconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (1.33)
Requirement already satisfied: PyYAML>=5.3 in c:\users\henri\miniconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (6.0.2)
Requirement already satisfied: typing-extensions>=4.7 in c:\users\henri\miniconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (4.12.2)
Requirement already satisfied: packaging>=23.2 in c:\users\henri\miniconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (24.2)
Requirement already satisfied: pydantic>=2.7.4 in c:\users\henri\miniconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (2.10.3)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\henri\miniconda3\lib\site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (2.1)
Requirement already satisfied: langchain-community<0.4.0,>=0.3.0 in c:\users\henri\miniconda3\lib\site-packages (from langchain_experimental) (0.3.25)
Requirement already satisfied: langchain<1.0.0,>=0.3.25 in c:\users\henri\miniconda3\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.3.25)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\users\henri\miniconda3\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.0.41)
Requirement already satisfied: requests<3,>=2 in c:\users\henri\miniconda3\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.32.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\henri\miniconda3\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (3.12.13)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in c:\users\henri\miniconda3\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.4.0 in c:\users\henri\miniconda3\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.9.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\henri\miniconda3\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.4.0)
Requirement already satisfied: numpy>=2.1.0 in c:\users\henri\miniconda3\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.2.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\henri\miniconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\henri\miniconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\henri\miniconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\henri\miniconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\henri\miniconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in c:\users\henri\miniconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\henri\miniconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.20.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\henri\miniconda3\lib\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\henri\miniconda3\lib\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\henri\miniconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\users\henri\miniconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (3.10.18)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\users\henri\miniconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in c:\users\henri\miniconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (0.23.0)
Requirement already satisfied: anyio in c:\users\henri\miniconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (4.9.0)
Requirement already satisfied: certifi in c:\users\henri\miniconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (2025.10.5)
Requirement already satisfied: httpcore==1.* in c:\users\henri\miniconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (1.0.9)
Requirement already satisfied: idna in c:\users\henri\miniconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\henri\miniconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\henri\miniconda3\lib\site-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\henri\miniconda3\lib\site-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (2.27.1)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\henri\miniconda3\lib\site-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.1.0)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\henri\miniconda3\lib\site-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\henri\miniconda3\lib\site-packages (from requests<3,>=2->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\henri\miniconda3\lib\site-packages (from requests<3,>=2->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.3.0)
Requirement already satisfied: greenlet>=1 in c:\users\henri\miniconda3\lib\site-packages (from SQLAlchemy<3,>=1.4->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (3.2.3)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\henri\miniconda3\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.1.0)
Requirement already satisfied: tokenizers>=0.19.1 in c:\users\henri\miniconda3\lib\site-packages (from langchain_huggingface) (0.21.1)
Requirement already satisfied: huggingface-hub>=0.33.4 in c:\users\henri\miniconda3\lib\site-packages (from langchain_huggingface) (0.35.3)
Requirement already satisfied: filelock in c:\users\henri\miniconda3\lib\site-packages (from huggingface-hub>=0.33.4->langchain_huggingface) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\henri\miniconda3\lib\site-packages (from huggingface-hub>=0.33.4->langchain_huggingface) (2025.3.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\henri\miniconda3\lib\site-packages (from huggingface-hub>=0.33.4->langchain_huggingface) (4.67.1)
Requirement already satisfied: colorama in c:\users\henri\miniconda3\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.33.4->langchain_huggingface) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\henri\miniconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.51->langchain_text_splitters) (1.3.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
docs = [doc for doc in df.decisao if isinstance(doc, str)]

text_splitter = RecursiveCharacterTextSplitter(
    # Set a really small chunk size, just to show.
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len,
    is_separator_regex=False,
)

# texts = text_splitter.split_documents(docs[0])
texts = text_splitter.split_text(docs[0])
print(texts[0])

SENTENÇA

Processo Digital nº:	1014984-85.2025.8.26.0554
Classe - Assunto	Procedimento Comum Cível - Tratamento médico-hospitalar
Requerente:	Amil Assistencia Médica Internacional S/A
Requerido:	Antonio Vanderly Lima e outro





Juiz(a) de Direito: Dr(a). Alberto Gentil de Almeida Pedroso

Vistos.

In [5]:
from langchain_text_splitters import CharacterTextSplitter
docs = [doc for doc in df.decisao if isinstance(doc, str)]

text_splitter = CharacterTextSplitter(
    separator=r"(fls. \d{1,3}/\d{1,3})",
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len,
    is_separator_regex=True,
)
# texts = text_splitter.split_documents(docs[0])
texts = text_splitter.split_text(docs[0])
print(texts[0])

Created a chunk of size 1628, which is longer than the specified 1000

SENTENÇA

Processo Digital nº:	1014984-85.2025.8.26.0554
Classe - Assunto	Procedimento Comum Cível - Tratamento médico-hospitalar
Requerente:	Amil Assistencia Médica Internacional S/A
Requerido:	Antonio Vanderly Lima e outro





Juiz(a) de Direito: Dr(a). Alberto Gentil de Almeida Pedroso

Vistos.

AMIL ASSISTÊNCIA MÉDICA INTERNACIONAL S.A. ingressou com ação de nulidade contratual em face de ANTONIO VANDERLY LIMA E OUTRO, alegando, em síntese, que em 01 de agosto de 2024 o requerido aderiu a plano de saúde da autora por meio de proposta firmada em nome da pessoa jurídica demandada, sendo que na ocasião preencheu a declaração de saúde, afirmando que gozava de plena saúde, respondendo negativamente às perguntas relacionadas a doenças ou lesões preexistentes, firmando o documento ao final. Ocorre que poucos meses após a contratação do plano, o réu buscou pronto-atendimento e restou evidenciado que era portador de dislipidemia, asma e dor torácica, o que não foi declarado no ato da contratação, mesmo já possuindo conhecimento da preexistência das patologias, que se declaradas sujeitariam o requerido à cobertura parcial temporária. Sustenta que houve fraude, sendo legítima a recusa de cobertura exarada pela ré, pois violada a boa-fé objetiva pelo usuário. Pugna pela procedência da ação, a fim de que seja reconhecida a fraude perpetrada, com consequente autorização da abstenção de atendimentos, cancelamento do contrato ou, alternativamente, cumprimento do período de CPT, condenação do réu na restituição dos valores pagos a título de reembolso, inclusive no curso da ação. Juntou documentos (

In [6]:
from langchain_experimental.text_splitter import SemanticChunker
# from langchain_openai import OpenAIEmbeddings
from langchain_huggingface import HuggingFaceEmbeddings
docs = [doc for doc in df.decisao if isinstance(doc, str)]

model_name = "rufimelo/bert-large-portuguese-cased-sts"
# model_kwargs = {'device': 'cpu'}
model_kwargs = {'device': 'cuda'}
encode_kwargs = {'normalize_embeddings': False}
embeddings = HuggingFaceEmbeddings(
        model_name=model_name,
        model_kwargs=model_kwargs,
        encode_kwargs=encode_kwargs,
    )

# text_splitter = SemanticChunker(embeddings, breakpoint_threshold_type="percentile", breakpoint_threshold=0.5)
text_splitter = SemanticChunker(embeddings, breakpoint_threshold_type="gradient", breakpoint_threshold_amount  = 0.5)
# text_splitter = SemanticChunker(embeddings, breakpoint_threshold_type="standard_deviation", breakpoint_threshold=0.5)

# texts = text_splitter.split_documents(docs[0])
texts = text_splitter.split_text(docs[0])
print(texts[0])

Invalid model-index. Not loading eval results into CardData.
Invalid model-index. Not loading eval results into CardData.

SENTENÇA

Processo Digital nº:	1014984-85.2025.8.26.0554
Classe - Assunto	Procedimento Comum Cível - Tratamento médico-hospitalar
Requerente:	Amil Assistencia Médica Internacional S/A
Requerido:	Antonio Vanderly Lima e outro





Juiz(a) de Direito: Dr(a).

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
docs = [doc for doc in df.decisao if isinstance(doc, str)]
tfidf_vect.fit(docs)
X =  tfidf_vect.transform(docs)
pd.DataFrame(X.toarray(), columns=tfidf_vect.get_feature_names_out()).head()

,0,00,000,0000,0001,0002,0003,0008,0011,0013282,...,ótica,ônus,última,último,últimos,única,único,únicos,úteis,útil
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.037996,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

docs = [doc for doc in df.decisao if isinstance(doc, str)]
clean_text = list()
stop = stopwords.words('portuguese')
snowball_stemmer = SnowballStemmer("portuguese") # Specify language for SnowballStemmer
for text in docs:
    words = word_tokenize(text)
    separator = ' '
    filtered_words = [word.lower() for word in words if word not in stop and word.isalpha()]
    stemmed_words = [snowball_stemmer.stem(word) for word in filtered_words if len(word) > 2]
    clean_text.append(separator.join(stemmed_words))
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(clean_text)
X =  tfidf_vect.transform(clean_text)
pd.DataFrame(X.toarray(), columns=tfidf_vect.get_feature_names_out()).head()

,aba,abaix,abal,abandon,abarc,abdom,abdomin,abdominal,abdominoplast,abdômen,...,órgã,órtes,ósse,ótic,ônus,úlcer,últim,únic,úte,útil
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.14121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [65]:
%pip install langchain_huggingface

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting langchain_huggingface
  Downloading langchain_huggingface-0.3.1-py3-none-any.whl.metadata (996 bytes)
Collecting langchain-core<1.0.0,>=0.3.70 (from langchain_huggingface)
  Downloading langchain_core-0.3.77-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: tokenizers>=0.19.1 in c:\users\henri\anaconda3\lib\site-packages (from langchain_huggingface) (0.21.1)
Collecting huggingface-hub>=0.33.4 (from langchain_huggingface)
  Downloading huggingface_hub-0.35.3-py3-none-any.whl.metadata (14 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<1.0.0,>=0.3.70->langchain_huggingface)
  Downloading langsmith-0.4.31-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\henri\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (9.0.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\henri\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (1.33)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in c:\users\henri\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (6.0.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\henri\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (4.12.2)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\henri\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (24.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\henri\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (2.10.3)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\henri\anaconda3\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (2.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\henri\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in c:\users\henri\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (3.10.18)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\henri\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\henri\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (2.32.3)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\henri\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (0.23.0)
Requirement already satisfied: anyio in c:\users\henri\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (4.7.0)
Requirement already satisfied: certifi in c:\users\henri\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\henri\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (1.0.2)
Requirement already satisfied: idna in c:\users\henri\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (3.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\henri\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\henri\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\henri\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (2.27.1)
Requirement already satisfied: filelock in c:\users\henri\anaconda3\lib\site-packages (from huggingface-hub>=0.33.4->langchain_huggingface) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\henri\anaconda3\lib\site-packages (from huggingface-hub>=0.33.4->langchain_huggingface) (2025.3.2)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\henri\anaconda3\lib\site-packages (from huggingface-hub>=0.33.4->langchain_huggingface) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\henri\anaconda3\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\henri\anaconda3\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (2.3.0)
Requirement already satisfied: colorama in c:\users\henri\anaconda3\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.33.4->langchain_huggingface) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\henri\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain_huggingface) (1.3.0)
Downloading langchain_huggingface-0.3.1-py3-none-any.whl (27 kB)
Downloading langchain_core-0.3.77-py3-none-any.whl (449 kB)
Downloading langsmith-0.4.31-py3-none-any.whl (386 kB)
Downloading huggingface_hub-0.35.3-py3-none-any.whl (564 kB)
   ---------------------------------------- 0.0/564.3 kB ? eta -:--:--
   --------------------------------------- 564.3/564.3 kB 20.1 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, langsmith, langchain-core, langchain_huggingface

  Attempting uninstall: huggingface-hub

    Found existing installation: huggingface-hub 0.31.4

    Uninstalling huggingface-hub-0.31.4:

      Successfully uninstalled huggingface-hub-0.31.4

   ---------------------------------------- 0/4 [huggingface-hub]
   ---------------------------------------- 0/4 [huggingface-hub]
   ---------------------------------------- 0/4 [huggingface-hub]
   ---------------------------------------- 0/4 [huggingface-hub]
   ---------------------------------------- 0/4 [huggingface-hub]
   ---------------------------------------- 0/4 [huggingface-hub]
  Attempting uninstall: langsmith
   ---------------------------------------- 0/4 [huggingface-hub]
    Found existing installation: langsmith 0.3.43
   ---------------------------------------- 0/4 [huggingface-hub]
    Uninstalling langsmith-0.3.43:
   ---------------------------------------- 0/4 [huggingface-hub]
      Successfully uninstalled langsmith-0.3.43
   ---------------------------------------- 0/4 [huggingface-hub]
   ---------- ----------------------------- 1/4 [langsmith]
   ---------- ----------------------------- 1/4 [langsmith]
   ---------- ----------------------------- 1/4 [langsmith]
  Attempting uninstall: langchain-core
   ---------- ----------------------------- 1/4 [langsmith]
    Found existing installation: langchain-core 0.3.63
   ---------- ----------------------------- 1/4 [langsmith]
   -------------------- ------------------- 2/4 [langchain-core]
    Uninstalling langchain-core-0.3.63:
   -------------------- ------------------- 2/4 [langchain-core]
      Successfully uninstalled langchain-core-0.3.63
   -------------------- ------------------- 2/4 [langchain-core]
   -------------------- ------------------- 2/4 [langchain-core]
   -------------------- ------------------- 2/4 [langchain-core]
   -------------------- ------------------- 2/4 [langchain-core]
   -------------------- ------------------- 2/4 [langchain-core]
   -------------------- ------------------- 2/4 [langchain-core]
   ---------------------------------------- 4/4 [langchain_huggingface]

Successfully installed huggingface-hub-0.35.3 langchain-core-0.3.77 langchain_huggingface-0.3.1 langsmith-0.4.31
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 3.6.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2025.3.2 which is incompatible.
langchain 0.3.25 requires langsmith<0.4,>=0.1.17, but you have langsmith 0.4.31 which is incompatible.
langchain-community 0.3.24 requires langsmith<0.4,>=0.1.125, but you have langsmith 0.4.31 which is incompatible.

In [8]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_experimental.text_splitter import SemanticChunker

model_name = "rufimelo/bert-large-portuguese-cased-sts"
# model_kwargs = {'device': 'cpu'}
model_kwargs = {'device': 'cuda'}
encode_kwargs = {'normalize_embeddings': False}
embeddings = HuggingFaceEmbeddings(
        model_name=model_name,
        model_kwargs=model_kwargs,
        encode_kwargs=encode_kwargs,
    )

embedding_vector = embeddings.embed_documents(docs[:10])
print(f"Embedding Vector: {embedding_vector[0]}")

Invalid model-index. Not loading eval results into CardData.
Invalid model-index. Not loading eval results into CardData.

Embedding Vector: [-0.06262809038162231, -0.6388548016548157, 0.17517000436782837, -0.3026884198188782, 0.40578973293304443, 0.6939718127250671, 0.1810828298330307, -0.3629726767539978, -0.20557476580142975, 0.4895344376564026, -0.47032931447029114, -0.9379382729530334, 0.054791130125522614, -0.3345627188682556, -0.35920506715774536, 0.38084161281585693, -0.36974674463272095, 0.2962261140346527, -0.6452703475952148, 0.7761621475219727, 0.0886298418045044, -0.29029446840286255, -0.4828210473060608, 0.09680423885583878, 0.15526044368743896, -0.14138835668563843, 0.18460038304328918, 0.23536252975463867, -0.6545883417129517, -0.46470579504966736, -0.333027720451355, 0.3540523946285248, -0.9637960195541382, -0.7714542150497437, -0.2976924479007721, 0.4641692042350769, -0.37020111083984375, 0.13619092106819153, -0.6138437390327454, -0.33587774634361267, 0.11740376800298691, 0.5674645900726318, -0.03302827849984169, 0.6553581357002258, 0.7083343863487244, 0.9265084862709045, -0.0530051589012146, 0.14022895693778992, 0.023816201835870743, -0.11574188619852066, 0.6225390434265137, 0.5925663113594055, -0.2607593834400177, 0.44567787647247314, 0.6954305171966553, 0.21099841594696045, -0.5954704880714417, 0.07031647861003876, 0.7124440670013428, 0.2860189974308014, -0.023055342957377434, -0.34130796790122986, -0.7541437745094299, 0.4655206501483917, 0.1394275575876236, -0.6582173109054565, -0.37627407908439636, 0.7166366577148438, -0.5366252660751343, 0.2546398937702179, 0.03329794481396675, -0.27783581614494324, 0.24880903959274292, -0.12848000228405, 0.0771811380982399, -0.5706503391265869, 0.15348559617996216, -0.4408797025680542, -0.03493146598339081, -0.31545376777648926, 0.04400058090686798, -0.3241078555583954, -0.14603842794895172, 0.3875647783279419, -0.05428372323513031, 0.35079336166381836, -0.6701574325561523, -0.13424840569496155, 0.144610196352005, -0.17228750884532928, -0.1768960803747177, -0.0029342910274863243, -0.8743336200714111, -0.03718440979719162, 0.45202991366386414, 0.4406374394893646, -0.46424421668052673, -0.5750000476837158, 0.691163182258606, -0.167469322681427, 0.5251543521881104, -0.21639597415924072, -0.13647320866584778, 0.1483767032623291, 0.2666620910167694, 0.11285915970802307, 0.7568610906600952, 0.14479298889636993, -0.04456077143549919, -0.45401155948638916, 0.24838364124298096, -0.6490126848220825, -0.6564828157424927, -0.1380932629108429, 0.32017961144447327, 0.15319451689720154, -0.08992365002632141, 0.5494886636734009, 0.4569855034351349, -0.7766796350479126, -0.04991777241230011, 0.0017979368567466736, -0.13198623061180115, -0.33632755279541016, 0.6775563955307007, -0.5703048706054688, 0.4673166573047638, -0.21366631984710693, 0.1830107867717743, 0.33026957511901855, 0.2305322289466858, -0.38189923763275146, 0.696078896522522, 0.6542393565177917, 0.14349175989627838, -0.34675103425979614, 0.5464563965797424, -0.2828218936920166, 1.38833749294281, -0.5972227454185486, 0.04169096797704697, -0.40077608823776245, -0.15196268260478973, 0.24050156772136688, -0.12352519482374191, -0.6108522415161133, 0.032211266458034515, -0.2021825611591339, -0.964564323425293, -0.4481310546398163, 0.09055061638355255, -0.17534807324409485, -0.12248367071151733, 0.19883130490779877, 0.17120160162448883, -0.4630524814128876, -0.1596839427947998, -0.22625777125358582, -0.0534801259636879, 0.4670185148715973, 0.23692002892494202, -0.1996423900127411, -0.04471211135387421, 0.5279117226600647, 0.00512735266238451, 0.39332032203674316, -0.36187779903411865, -0.13939642906188965, 0.29413288831710815, 0.5696535110473633, 0.17721889913082123, -0.19447845220565796, 0.13785026967525482, -0.3119857907295227, -0.4118080735206604, 0.20452719926834106, -0.5797191262245178, -0.4279445707798004, -0.7131996154785156, -0.14423155784606934, -0.05757126957178116, -0.27612489461898804, -0.301483690738678, 0.3504587411880493, 0.632369875907898, 0.1333189606666565, 0.2661060690879822, -0.5135600566864014, 0.2509310841560364, -0.19007420539855957, 0.018876923248171806, 0.614363968372345, 0.09782098233699799, 0.5944244265556335, 0.09940443187952042, -0.10239626467227936, 0.4787859320640564, -0.02061174437403679, -0.1520536243915558, -0.6322696208953857, 0.1926160454750061, -0.22469326853752136, 0.189968079328537, 0.056073226034641266, -0.3424476385116577, -0.4365677833557129, -0.00664885900914669, 0.24220384657382965, 0.33054319024086, -0.005943303927779198, 0.750129759311676, -0.05576103553175926, -0.33428722620010376, -0.1653451770544052, 0.21305878460407257, 0.5880866050720215, -0.521016001701355, 0.27896183729171753, -0.017857715487480164, -0.141981840133667, 0.046124961227178574, -0.013335318304598331, 0.22185811400413513, -0.31831806898117065, 0.2411508560180664, -0.7484287619590759, -0.0871645137667656, -0.22629183530807495, 0.21593311429023743, -0.30922815203666687, 0.12692013382911682, 0.6771790981292725, -0.4593091607093811, 0.22400450706481934, 0.31302428245544434, -0.14201299846172333, -0.08017446100711823, 0.10798709094524384, -0.43097352981567383, 0.2778080701828003, 0.17616194486618042, 0.11328744888305664, 0.5839166641235352, -0.17100392282009125, -0.4935086965560913, 0.005130220204591751, 0.3995380997657776, 0.5011444687843323, -0.5779209136962891, 0.39959853887557983, 0.31867170333862305, -0.4369892477989197, 0.16648264229297638, 0.3422623872756958, -0.6797502040863037, -0.07451281696557999, 0.2778787612915039, -0.3021754026412964, -0.7202309370040894, -0.0822661817073822, -0.5966575145721436, -0.025604721158742905, -0.09766760468482971, -0.5689118504524231, 0.07215917110443115, -0.20425957441329956, 0.02932831645011902, -0.06238638237118721, -0.03759738802909851, 0.43874868750572205, -0.512039065361023, -0.13715039193630219, 0.16625992953777313, 0.4239663779735565, -0.08706007897853851, -0.06800766289234161, 0.5354752540588379, 0.3329288959503174, -0.3516961932182312, -0.3386513888835907, 0.0024021221324801445, -0.34817707538604736, 0.26020532846450806, -0.33540117740631104, -0.02700294554233551, -0.5858933925628662, -0.23785454034805298, -0.36533766984939575, 0.09247415512800217, 0.1430583894252777, -0.36799171566963196, -0.1908464878797531, -0.6132476925849915, -0.03460972011089325, -0.3363557457923889, -0.07905526459217072, 0.23316101729869843, 0.13736456632614136, -0.03801144286990166, -0.16712699830532074, -0.447121798992157, 0.5788522958755493, 0.48895031213760376, -0.05520934611558914, -0.36625808477401733, -0.49253609776496887, -0.17279256880283356, 0.2174217700958252, 0.09109170734882355, -0.45366090536117554, 0.09522879868745804, 0.016949856653809547, 0.3532060980796814, -0.6697883605957031, -0.002006722614169121, 0.19372773170471191, 0.570797860622406, 0.17444166541099548, -0.11244344711303711, 0.5590630769729614, 0.019858499988913536, -0.2823263108730316, -0.4263274073600769, 0.20647558569908142, -0.4394010007381439, -0.42740076780319214, -1.0601834058761597, -0.30425816774368286, 0.1025790423154831, -0.4518823027610779, -0.7905746698379517, 0.22934669256210327, -0.8679223656654358, -0.46755164861679077, -0.28186118602752686, -0.4461231827735901, 0.7086328268051147, 0.30863630771636963, -0.4219881594181061, 0.6573930978775024, -0.023280948400497437, -0.23267726600170135, -0.030017923563718796, -0.4035855531692505, 0.07490532845258713, 0.6313396096229553, 0.5645122528076172, 0.0124614667147398, -0.2684415578842163, -0.2531701922416687, 0.21214726567268372, -0.5499929189682007, -0.07772328704595566, -0.4250689446926117, 0.496320515871048, 0.5819371938705444, -0.5716768503189087, 0.3479357957839966, 0.07196655869483948, 0.0775199756026268, 0.022207297384738922, 0.16325196623802185, -0.16212806105613708, 0.03199312090873718, -0.17946182191371918, -0.24300286173820496, -0.14337879419326782, 0.3356362283229828, -0.1275072693824768, 0.23584210872650146, 0.3795199394226074, -0.6010009050369263, -0.31524673104286194, 0.4484202265739441, 0.38046491146087646, -0.14818669855594635, -0.30131059885025024, 0.08453136682510376, -0.15540863573551178, -0.4253404438495636, 0.4029851257801056, 0.7667822241783142, 0.4365187883377075, 0.38143450021743774, -0.4068794846534729, -0.7520416975021362, -0.2554608881473541, 0.24651765823364258, 0.05435120686888695, 0.15393729507923126, -0.38732749223709106, 0.2268325388431549, -0.39996814727783203, -0.8427841663360596, -0.6735286712646484, 0.3081493377685547, 0.8382811546325684, -0.49013981223106384, 0.04638471081852913, 0.3766437768936157, -0.3341894745826721, 0.0006703780964016914, -0.08762010931968689, 0.41827303171157837, 0.013295882381498814, -0.1324595808982849, -0.6563830375671387, -0.01008546631783247, 0.14043498039245605, -0.7513120770454407, -0.4548398554325104, 0.5069712400436401, -0.11220819503068924, -0.1784210503101349, -0.24387529492378235, 0.4491632878780365, -0.5584086179733276, -0.1532757431268692, 0.10606242716312408, -0.7286344766616821, 0.37484174966812134, -0.30620670318603516, 0.1357824206352234, -0.36015763878822327, 0.44428956508636475, 0.7741801738739014, 0.0638287216424942, -0.9862737059593201, -0.09234977513551712, 0.29559648036956787, 1.3619589805603027, 0.47813165187835693, -0.2601563334465027, 0.27322718501091003, -0.21230968832969666, 0.4670318365097046, -0.6741751432418823, -0.09624878317117691, 0.38750097155570984, -0.30477750301361084, 0.020694971084594727, 0.26854896545410156, 0.43046098947525024, 0.2989357113838196, -0.18166303634643555, 0.2804652154445648, 0.23078113794326782, -1.1588330268859863, 0.29594647884368896, 0.38496577739715576, -0.09723447263240814, 0.4528677761554718, 0.5785101056098938, -0.4108598232269287, -0.6104292273521423, 0.14106668531894684, 2.609081506729126, -0.206466943025589, -0.3274410367012024, 0.20752644538879395, 0.3352804183959961, -1.0279598236083984, 0.19705796241760254, 0.41298916935920715, -0.16935837268829346, 0.0596325546503067, -0.020793696865439415, 0.7098249197006226, -0.6514884829521179, -0.32850128412246704, 0.014795711264014244, 0.4584408104419708, 0.4306069612503052, 0.21884073317050934, 0.08972884714603424, 0.08956662565469742, -0.1838626265525818, 0.4415878355503082, -0.33733564615249634, -0.41709768772125244, 0.10382707417011261, -0.35955220460891724, -0.40614476799964905, 0.15325531363487244, 0.7560504674911499, -0.14266251027584076, 0.8038984537124634, -0.635460615158081, 0.28929007053375244, -0.4593955874443054, -0.3483531177043915, 0.03229985386133194, 0.21830441057682037, -0.04823464900255203, 0.04869549721479416, 0.11460243165493011, -0.4641039967536926, -0.3564443588256836, 0.3922569155693054, 0.1707853376865387, -0.11380057036876678, 0.2288435697555542, 0.23622076213359833, -0.31283512711524963, -0.05698646977543831, -0.03402882069349289, 0.24649521708488464, -0.7960118055343628, -0.5189459323883057, -0.25176742672920227, -0.02534588985145092, -0.8963793516159058, 0.23251469433307648, -0.6943654417991638, 0.11662033945322037, 0.032583087682724, -0.06868992745876312, 0.31560784578323364, 0.1101357489824295, -0.8347480297088623, 0.0909484326839447, -0.7553446292877197, -0.13468506932258606, -0.3043949604034424, -0.5889863967895508, 0.9688102006912231, 0.2670639455318451, -0.09961649775505066, 0.190364807844162, -0.12239569425582886, -0.4463934898376465, 0.21059370040893555, -0.10838750004768372, -0.4639933407306671, -0.19086763262748718, -0.9341527223587036, -0.1354740858078003, -0.10075561702251434, 0.19929960370063782, -0.5984879732131958, 0.8008020520210266, -0.3650481104850769, -0.10782232880592346, 0.13349565863609314, 0.0948256254196167, -0.05802725628018379, -0.6172656416893005, 0.2348598837852478, -0.43197232484817505, 0.02639930695295334, 0.1143779456615448, -0.13672474026679993, 0.014279140159487724, 0.36645302176475525, -0.38556545972824097, 0.4648358225822449, 0.028001613914966583, 0.015328221023082733, 0.12549176812171936, -0.27956223487854004, -0.46180054545402527, 0.2734753489494324, -0.15086741745471954, 0.1576019525527954, -0.8076871037483215, 0.26913678646087646, -0.24908137321472168, -0.582233190536499, 0.17434494197368622, 0.2643163204193115, -0.34292489290237427, -0.2842816114425659, -0.04380393773317337, -0.12386391311883926, -0.3362003266811371, 0.2407923936843872, -0.23699422180652618, 0.004931981675326824, -0.24259620904922485, 0.16347572207450867, 0.10988152027130127, 0.021843306720256805, 0.5027186870574951, -0.9856839179992676, -0.05113732069730759, -0.004075748845934868, -0.4630586504936218, -0.18973910808563232, 0.015017830766737461, -0.16084681451320648, -0.2057274580001831, -0.754615068435669, -0.287741482257843, -0.41936132311820984, -0.16496148705482483, -1.2210783958435059, -0.312965989112854, -0.08930803835391998, -0.16083288192749023, -0.09224489331245422, -0.7053844332695007, 0.15129679441452026, -0.07140035927295685, -0.48860979080200195, 0.20355373620986938, -0.2380865216255188, -0.07151433080434799, 0.04182634502649307, -0.48701032996177673, -0.049889132380485535, -0.5144563913345337, 0.2205759882926941, 0.2073158323764801, -0.10146790742874146, -0.003830687142908573, -0.10247483849525452, -0.8491477966308594, 0.08127419650554657, -0.17060625553131104, -0.12729614973068237, 0.04244101792573929, -0.32344603538513184, -0.19701853394508362, -0.10137712955474854, 0.3744671642780304, -0.942878246307373, -0.180290088057518, 0.13718095421791077, -0.8521186113357544, 0.9385568499565125, -0.5519461631774902, 0.5374759435653687, 0.27436381578445435, -0.431477427482605, 0.09961654990911484, -0.41088250279426575, 0.2646006941795349, 0.1064339354634285, 0.7205001711845398, 0.15689167380332947, -0.3704181909561157, 0.542182445526123, 0.08597654104232788, 0.032747622579336166, -0.34731096029281616, 0.2192598581314087, -0.5530844926834106, 0.4706456661224365, 0.002055798890069127, -0.24183480441570282, 0.33503299951553345, -0.018474314361810684, 0.3112940192222595, 1.072012186050415, -0.2668777406215668, -0.16953445971012115, 0.41321462392807007, -0.2154778242111206, 0.4993751049041748, -0.20511701703071594, -0.0034862393513321877, -0.761773943901062, 0.5852853059768677, 0.09833994507789612, -0.5193043351173401, -0.11130648106336594, 0.17490540444850922, -0.33915138244628906, -0.48435866832733154, -0.46185189485549927, -0.12797632813453674, 0.30081501603126526, 0.33424651622772217, 0.1770472377538681, 0.15410032868385315, -0.2398524284362793, 0.6311386823654175, -0.4736998379230499, -0.18876641988754272, -0.10397346317768097, 0.11131931841373444, 0.040914252400398254, -0.32212525606155396, -0.11175213754177094, 1.2805038690567017, -0.33589333295822144, 0.18781989812850952, 0.021782822906970978, 0.8421722650527954, -0.14362236857414246, -0.39121854305267334, -0.16456085443496704, 0.30305227637290955, -0.16873213648796082, 1.026143193244934, -0.1626078486442566, -0.4385663568973541, 0.2602916359901428, -0.35135534405708313, 0.4720713496208191, 1.1702868938446045, 0.02351556159555912, -0.42703747749328613, -0.23940567672252655, -0.3220646381378174, -0.6035388112068176, -0.15134118497371674, 0.03235938027501106, -0.6934916973114014, -0.3674999475479126, 0.009157780557870865, 1.0020242929458618, 0.30206483602523804, -0.11142207682132721, -0.03391402214765549, 0.5575954914093018, 0.3256082832813263, -0.47164082527160645, 0.001483728177845478, 0.01676103100180626, 0.09319683909416199, 0.25326472520828247, 0.027628278359770775, -0.08865591883659363, -0.45157933235168457, 0.8476369976997375, 0.07290856540203094, -0.43460196256637573, 0.30764657258987427, 0.10493641346693039, 0.16869650781154633, -0.500089168548584, -0.1669895052909851, -0.7236231565475464, 0.24636411666870117, -0.11453041434288025, 0.18623661994934082, -0.3249942362308502, -0.22863954305648804, -0.31519925594329834, -0.22886031866073608, 0.8543795943260193, -0.9219270944595337, 0.052510082721710205, 0.33962389826774597, 0.03920101374387741, 0.26615726947784424, 0.04892353713512421, 0.4607912302017212, -0.17225605249404907, -0.0017971210181713104, 0.010059586726129055, -0.2252737581729889, 1.1633497476577759, -0.4280156195163727, 0.047065410763025284, 0.1944727897644043, 0.00023140199482440948, 0.8761690855026245, -0.04313447326421738, 0.0557662770152092, 0.07303564250469208, -0.055119507014751434, -0.45304566621780396, -0.2365615963935852, 0.22594276070594788, 0.005713663995265961, 0.21026241779327393, -0.35999244451522827, -0.18537859618663788, -0.13006755709648132, 0.36098819971084595, -0.11356639117002487, 0.07698513567447662, -0.37297749519348145, -0.5158838033676147, -0.3667338490486145, 0.0074859801679849625, 0.7141655087471008, 0.3389282822608948, -0.6814092397689819, -0.5454496145248413, 0.23811203241348267, 0.2973130941390991, 0.06068997457623482, -0.11622367054224014, 0.3622816205024719, -0.35376307368278503, -0.023702558130025864, -0.277079701423645, 0.21559280157089233, -0.9204124808311462, -0.10827876627445221, 0.09651139378547668, -0.21029968559741974, 0.3857457637786865, -0.5296940207481384, -0.07005443423986435, -0.21900098025798798, -0.43887683749198914, -0.0033603901974856853, -0.2113070785999298, 0.34555816650390625, 0.4417450428009033, -0.374234676361084, -0.2083439826965332, -0.20905084908008575, 0.09301073849201202, -0.004644337110221386, -0.6874938011169434, -0.29416173696517944, 1.3425215482711792, -0.193379208445549, 0.8316983580589294, -0.4929032027721405, -0.25976744294166565, -0.2941208481788635, 0.1107499748468399, 0.19438284635543823, 0.39319556951522827, 0.4087202548980713, 0.13828954100608826, -0.05784377455711365, 0.8259837627410889, -0.20837166905403137, 0.9542795419692993, 0.33954256772994995, -0.19292695820331573, -0.7008519768714905, 0.6045763492584229, -0.3299233317375183, -0.19970890879631042, 0.4853975176811218, 0.32224324345588684, -0.10597911477088928, 0.4521881937980652, 0.453249454498291, -0.26647478342056274, -0.07765612006187439, 0.4797365069389343, -0.008139440789818764, -0.2684343457221985, 0.8423914909362793, -0.09001319110393524, -0.06535858660936356, -0.14102303981781006, 0.16711927950382233, 0.2243824601173401, -0.3658604621887207, -0.3971829414367676, 0.3742465674877167, -0.17433109879493713, -0.4954991042613983, -0.21400029957294464, -0.3405933976173401, 0.5777488946914673, -0.3632572591304779, 0.009291578084230423, 0.24496331810951233, 0.07260186970233917, -0.32104986906051636, -0.4027533233165741, -0.317195862531662, 0.007286997511982918, 0.3163355588912964, -0.28459641337394714, 0.6004188060760498, -0.1499020904302597, 0.18376484513282776, -0.17728453874588013, -0.27140122652053833, 0.1784825623035431, 0.07613162696361542, 0.05324903875589371, 0.28194838762283325, 0.03867523372173309, -1.1381852626800537, -0.17160016298294067, -0.4334225058555603, -0.20837906002998352, -0.33072906732559204, -0.3400473892688751, -0.15779615938663483, -0.6079156398773193, -0.3655545711517334, -0.14129894971847534, -0.15928560495376587, 0.037007737904787064, -0.06500884890556335, -0.4645611345767975, 0.47217535972595215, 0.19243934750556946, -0.20625078678131104, -0.2998422384262085, -0.5396368503570557, 1.0572651624679565, -0.6303541660308838, -0.26113659143447876, -0.6819804906845093, 0.06939639151096344, 0.5019964575767517, 0.19322392344474792, 0.3254929780960083, 0.30930542945861816, -0.0804932564496994, -0.5198260545730591, -0.31227168440818787, -0.165317565202713, -0.6626051068305969, 0.11273977160453796, -0.17614582180976868, 0.5098118782043457, 0.4910743832588196, -0.039746616035699844, -0.12756390869617462, 0.2352989763021469, -0.15487772226333618, 0.10398635268211365, 1.01949143409729, -0.13012976944446564, -0.33212125301361084, 0.4707294702529907, -0.15169507265090942, -0.02164240926504135, 0.12796980142593384, -0.40051135420799255, -0.24008014798164368, 0.3397265672683716, 0.1097102016210556, 0.3099100589752197, -0.009261617437005043, 0.0037062191404402256, -0.08611354231834412, 0.16576117277145386, 0.821379542350769, -0.39472368359565735, -0.2761458158493042, 0.06630346179008484, -0.028879351913928986, 0.18429294228553772, -0.06026295945048332, -0.051388487219810486, 0.18951351940631866, 0.4532822370529175, -0.9388924837112427, 0.11453455686569214, -0.520850