In [5]:
# %pip install BeautifulSoup4 requests pandas
%pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------------ --------------------- 1.8/4.0 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 10.6 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup
import warnings
from requests.packages.urllib3.exceptions import InsecureRequestWarning

warnings.simplefilter('ignore', InsecureRequestWarning)
url = 'https://www.imdb.com/chart/top/?ref_=nv_mv_250&sort=rank%2Casc'
headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'}
session = requests.Session()
req = session.get(url, verify=False, headers=headers, timeout=10)
time.sleep(5)
soup = BeautifulSoup(req.text, 'lxml')
lista = soup.find_all('a')

best_rated = list()
rows = list()
for item in lista:
    if 'href' in item.attrs and 'title' in item.attrs['href'] and 'ref_=chttp_t_' in item.attrs['href']:
        best_rated.append('https://www.imdb.com'+item.attrs['href'])

for url in set(best_rated):
    response = session.get(url, verify=False, headers=headers, timeout=10)
    soup = BeautifulSoup(response.text, 'lxml')
    dicionario = dict()
    sumario_reviewers = ''
    dicionario['nome'] = soup.find_all('title')[0].text
    dicionario['nota'] = soup.find_all("span",{'class':"ipc-rating-star--rating"})[0].text
    dicionario['publico'] = soup.find_all('span',{'class':'vote-count'})[0].text
    dicionario['sumario_ai'] = soup.find_all('div',{'class':"ipc-html-content-inner-div",'role':'presentation'})[0].text
    for item in soup.find_all('div',{'class':"ipc-html-content-inner-div",'role':'presentation'})[1:]:
        sumario_reviewers += ' ' + item.text
    dicionario['sumario_reviewers'] = sumario_reviewers
    rows.append(dicionario)
    time.sleep(1)
    
# pd.DataFrame(rows).to_excel('imdb_25.xlsx', index=False)
pd.DataFrame(rows)

,nome,nota,publico,sumario_ai,sumario_reviewers
0,Três Homens em Conflito (1966) - IMDb,8.8,870.8K,"Reviewers say 'The Good, the Bad and the Ugly'...","Gosh, The Good, the Bad, and the Ugly, I fina..."
1,O Senhor dos Anéis: O Retorno do Rei (2003) - ...,9.0,2113.9K,"Reviewers say 'The Lord of the Rings' trilogy,...",I've just re-watched The Lord of the Rings tr...
2,O Senhor dos Anéis: As Duas Torres (2002) - IMDb,8.8,1907.4K,Reviewers say 'The Lord of the Rings: The Two ...,"""The Lord of the Rings: The Two Towers"" is an..."
3,O Poderoso Chefão (1972) - IMDb,9.2,2169.2K,Reviewers say 'The Godfather' is acclaimed for...,"The acting was simply amazing, what else coul..."
4,A Felicidade Não se Compra (1946) - IMDb,8.6,535.9K,Reviewers say 'It's a Wonderful Life' is celeb...,This film has become a Christmas tradition in...
5,Os Sete Samurais (1954) - IMDb,8.6,391.6K,Reviewers say 'Seven Samurai' is highly rated ...,Akira Kurosawa's masterpiece... The Japanese ...
6,O Resgate do Soldado Ryan (1998) - IMDb,8.6,1598.6K,Reviewers say 'Saving Private Ryan' is acclaim...,It's been over a year since first seeing Savi...
7,O Silêncio dos Inocentes (1991) - IMDb,8.6,1670.6K,Reviewers say 'The Silence of the Lambs' delve...,Brilliant Best Picture of 1991 that never get...
8,Forrest Gump: O Contador de Histórias (1994) -...,8.8,2429.6K,Reviewers say 'Forrest Gump' is celebrated for...,"Every once in a while, something comes along ..."
9,O Senhor dos Anéis: A Sociedade do Anel (2001)...,8.9,2148.7K,Reviewers say 'The Lord of the Rings: The Fell...,An incredible feat\nEnthrals anew every time\...
10,À Espera de um Milagre (1999) - IMDb,8.6,1517.4K,Reviewers say 'The Green Mile' is acclaimed fo...,Frank Darabont returns to the directors chair...
11,Um Estranho no Ninho (1975) - IMDb,8.7,1134.6K,Reviewers say 'One Flew Over the Cuckoo's Nest...,Milos Forman's One Flew Over the Cuckoo's Nes...
12,Seven - Os Sete Crimes Capitais (1995) - IMDb,8.6,1960.2K,"Reviewers say 'Se7en' is a gripping, unsettlin...",A retiring Detective and a young rookie are h...
13,Um Sonho de Liberdade (1994) - IMDb,9.3,3111.2K,Reviewers say 'The Shawshank Redemption' is ce...,This movie is not your ordinary Hollywood fli...
14,Star Wars: Episódio V - O Império Contra-Ataca...,8.7,1469.9K,Reviewers say 'The Empire Strikes Back' distin...,"An excellent sequel to Star Wars, this is eas..."
15,Interestelar (2014) - IMDb,8.7,2419.8K,Reviewers say 'Interstellar' is acclaimed for ...,Interstellar is a movie like no other. Unlike...
16,Pulp Fiction: Tempo de Violência (1994) - IMDb,8.8,2377.6K,Reviewers say 'Pulp Fiction' is acclaimed for ...,Viewers are taken on a ride through three dif...
17,Os Bons Companheiros (1990) - IMDb,8.7,1354.6K,Reviewers say 'Goodfellas' is a cinematic mast...,If there was one word that I could use to des...
18,A Lista de Schindler (1993) - IMDb,9.0,1551K,Reviewers say 'Schindler's List' is acclaimed ...,Fantastic screening of the bloody history. Wa...
19,Clube da Luta (1999) - IMDb,8.8,2526.5K,Reviewers say 'Fight Club' is celebrated for i...,Beleive me if you want to feel this movie to ...
20,12 Homens e uma Sentença (1957) - IMDb,9.0,952.5K,Reviewers say '12 Angry Men' is acclaimed for ...,This is one of those movies where everything ...
21,Batman: O Cavaleiro das Trevas (2008) - IMDb,9.1,3086.7K,Reviewers say 'The Dark Knight' is celebrated ...,*level of enjoyment*\n#10\ntop tier - from st...
22,O Poderoso Chefão: Parte II (1974) - IMDb,9.0,1457.4K,Reviewers say 'The Godfather Part II' is accla...,One of the all time greats. Or probably the a...
23,Matrix (1999) - IMDb,8.7,2194.9K,Reviewers say 'The Matrix' is a groundbreaking...,What if I told you the Matrix is not a Sci-Fi...
24,A Origem (2010) - IMDb,8.8,2741.7K,Reviewers say 'Inception' is lauded for its am...,You only get to watch this for the first time...

In [31]:
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup

headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'}
session = requests.Session()
url = 'https://g1.globo.com/'
response = session.get(url, verify=False, headers=headers, timeout=10)
soup = BeautifulSoup(response.text, 'lxml')

lista = soup.find_all('a',{'class': "feed-post-link gui-color-primary gui-color-hover"})
noticias =  [w.text for w in lista]
links = [w.attrs['href'] for w in lista]
pd.DataFrame({'noticias': noticias, 'links': links})

c:\Users\henri\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'g1.globo.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,noticias,links
0,Zelensky pede mísseis Tomahawk a Trump para at...,https://g1.globo.com/mundo/noticia/2025/10/17/...
1,Míssil americano desejado por Zelensky é mais ...,https://g1.globo.com/mundo/noticia/2025/10/17/...
2,Maduro posiciona tropas no Caribe após bombard...,https://g1.globo.com/mundo/noticia/2025/10/17/...
3,Quem é o comandante americano que deixou cargo...,https://g1.globo.com/mundo/noticia/2025/10/17/...
4,Trabalhador de app ganha mais e tem carga horá...,https://g1.globo.com/trabalho-e-carreira/notic...
5,Como a China conseguiu encontrar 'ponto fraco'...,https://g1.globo.com/economia/noticia/2025/10/...
6,Fim de uma era: eleição de domingo na Bolívia ...,https://g1.globo.com/mundo/noticia/2025/10/17/...
7,Príncipe Andrew renuncia a títulos reais após ...,https://g1.globo.com/mundo/noticia/2025/10/17/...

In [32]:
%pip install selenium

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting selenium
  Downloading selenium-4.36.0-py3-none-any.whl.metadata (7.5 kB)
Collecting urllib3<3.0,>=2.5.0 (from urllib3[socks]<3.0,>=2.5.0->selenium)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting trio<1.0,>=0.30.0 (from selenium)
  Downloading trio-0.31.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting certifi>=2025.6.15 (from selenium)
  Downloading certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)
Collecting typing_extensions<5.0,>=4.14.0 (from selenium)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\henri\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\henri\anaconda3\lib\site-packages (from trio<1.0,>=0.30.0->selenium) (24.3.0)
Requirement already satisfied: sortedcontainers in c:\users\henri\anaconda3\lib\site-packages (from trio<1.0,>=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\henri\anaconda3\lib\site-packages (from trio<1.0,>=0.30.0->selenium) (3.7)
Collecting outcome (from trio<1.0,>=0.30.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\henri\anaconda3\lib\site-packages (from trio<1.0,>=0.30.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\henri\anaconda3\lib\site-packages (from trio<1.0,>=0.30.0->selenium) (1.17.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\henri\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\henri\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.30.0->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\henri\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.14.0)
Downloading selenium-4.36.0-py3-none-any.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 9.6/9.6 MB 119.5 MB/s eta 0:00:00
Downloading trio-0.31.0-py3-none-any.whl (512 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, urllib3, typing_extensions, outcome, certifi, trio, trio-websocket, selenium

  Attempting uninstall: urllib3

    Found existing installation: urllib3 2.3.0

    Uninstalling urllib3-2.3.0:

      Successfully uninstalled urllib3-2.3.0

   ----- ---------------------------------- 1/8 [urllib3]
  Attempting uninstall: typing_extensions
   ----- ---------------------------------- 1/8 [urllib3]
    Found existing installation: typing_extensions 4.12.2
   ----- ---------------------------------- 1/8 [urllib3]
    Uninstalling typing_extensions-4.12.2:
   ----- ---------------------------------- 1/8 [urllib3]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
      Successfully uninstalled typing_extensions-4.12.2
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
  Attempting uninstall: certifi
   ---------- ----------------------------- 2/8 [typing_extensions]
    Found existing installation: certifi 2025.4.26
   ---------- ----------------------------- 2/8 [typing_extensions]
    Uninstalling certifi-2025.4.26:
   ---------- ----------------------------- 2/8 [typing_extensions]
      Successfully uninstalled certifi-2025.4.26
   ---------- ----------------------------- 2/8 [typing_extensions]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------------ --------- 6/8 [trio-websocket]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ---------------------------------------- 8/8 [selenium]

Successfully installed certifi-2025.10.5 outcome-1.3.0.post0 selenium-4.36.0 trio-0.31.0 trio-websocket-0.12.2 typing_extensions-4.13.2 urllib3-2.5.0 wsproto-1.2.0
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.19.0 requires botocore<1.36.4,>=1.36.0, but you have botocore 1.40.50 which is incompatible.

In [33]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.ingresso.com/recife/home/cinemas/cinemark-riomar-recife'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'lxml')
termos = ['Cinemark', 'preços']

for w in termos:
    if w in str(soup):
        print('Contém a palavra',w,'no código fonte.\n')
    else:
        print('Não contém a palavra',w,'no código fonte.\n')

Não contém a palavra Cinemark no código fonte.

Não contém a palavra preços no código fonte.

In [ ]:
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains

# Set up Chrome options to run in headless mode (optional)
options = Options()
options.add_argument("--window-size=1920,1080")
# options.add_argument("--headless")

# Initialize the Chrome WebDriver
# If using headless mode: driver = webdriver.Chrome(options=options)
driver = webdriver.Chrome(options=options)
# cinemas = ['https://www.ingresso.com/cinema/uci-kinoplex-shopping-recife?city=recife', 
        #    'https://www.ingresso.com/cinema/cinemark-riomar-recife?city=recife']
url = 'https://www.ingresso.com/cinema/uci-kinoplex-shopping-recife?city=recife'
driver.get(url)
time.sleep(5)
html_source = driver.page_source
soup = BeautifulSoup(html_source, 'lxml')
id = [item.attrs['id'] for item in soup.find_all('div', id=True, attrs={'class': "bg-ing-neutral-600 relative my-5 scroll-mt-[250px] overflow-hidden rounded-[10px] p-4"})]
titles = [item.text for item in soup.find_all('a',attrs = {'class': 'text-white no-underline'})]
precos = list()
button = driver.find_element(By.ID, "rcc-confirm-button")
if button:
    ActionChains(driver) \
    .click(button) \
    .perform()
for item in id:
    element = driver.find_element(By.XPATH, f'//*[@id="{item}"]/div[3]/div[1]/button[2]')
    if element:
        ActionChains(driver) \
        .click(element) \
        .perform()
        time.sleep(5)
        html_preco = driver.page_source
        soup = BeautifulSoup(html_preco, 'lxml')
        precos.append([item.text for item in soup.find_all('div', attrs= {'class':"text-xl text-white"})])
        driver.refresh()
        time.sleep(5)
driver.quit()

precos_finais = list()
for _, row in pd.DataFrame({'filmes': titles, 'precos': precos}).iterrows():
    preco_filme = dict()
    preco_filme['filme'] = row.filmes
    for filme in row['precos']:
        preco_filme[filme.split(': ')[0]] = filme.split(': ')[1]
        # preco_filme['preco'] = filme.split(': ')[1]
    precos_finais.append(preco_filme)
pd.DataFrame(precos_finais)

In [ ]:
import requests
from datetime import date
from bs4 import BeautifulSoup
from urllib.parse import quote
from tqdm import tqdm
import warnings
from requests.packages.urllib3.exceptions import InsecureRequestWarning
import pandas as pd

# Remove warnings a cada requisição
warnings.simplefilter('ignore', InsecureRequestWarning)

# Função principal para extração
def extract_decisoes_tjsp_grau1(links):
    dados = []  # Lista para armazenar os dados
    
    for link in links:
        session = requests.Session()
        req = session.get(link, verify=False)
        
        if "Não foi encontrado nenhum resultado correspondente à busca realizada" in req.text:
            print(f"Nenhum resultado encontrado para a URL: {link}")
            continue

        soupPrincipal = BeautifulSoup(req.content, 'html.parser')

        # Recupera o número total de resultados
        totalResultados = int(soupPrincipal.find("div", {"id": "resultados"}).find_all("table")[0].tr.td.text.strip().split("de ")[1])
        totalPaginas = totalResultados // 10 if totalResultados % 10 == 0 else (totalResultados // 10) + 1
        
        print(f"Iniciando coleta de dados para a URL: {link}")
        for i in tqdm(range(1, totalPaginas + 1)):
            url_paginate = f"https://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=roubo+OU+furto&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=01%2F01%2F2021&dadosConsulta.dtFim=31%2F12%2F2021&varasTreeSelection.values=&varasTreeSelection.text=&dadosConsulta.ordenacao=DESC"
            req = session.get(url_paginate, verify=False)
            soupPrincipal = BeautifulSoup(req.content, 'html.parser')
            
            for target in soupPrincipal.find_all('tr', {'class': 'fundocinza1'}):
                contador = 0
                linha = {
                    "numero_cnj": None,
                    "classe": None,
                    "assunto": None,
                    "magistrado": None,
                    "comarca": None,
                    "foro": None,
                    "vara": None,
                    "data_disponibilizacao": None,
                    "decisao": None,
                }

                for info in target.find_all('tr', {'class': 'fonte'}):
                    if contador == 0:
                        linha["numero_cnj"] = info.span.text.strip()
                    elif contador == 1:
                        linha["classe"] = info.td.text.strip().split("\n\t")[-1].strip()
                    elif contador == 2:
                        linha["assunto"] = info.td.text.strip().split("\n\t")[-1].strip()
                    elif contador == 3:
                        linha["magistrado"] = info.td.text.strip().split("\n\t")[-1].strip()
                    elif contador == 4:
                        linha["comarca"] = info.td.text.strip().split("\n\t")[-1].strip()
                    elif contador == 5:
                        linha["foro"] = info.td.text.strip().split("\n\t")[-1].strip()
                    elif contador == 6:
                        linha["vara"] = info.td.text.strip().split("\n\t")[-1].strip()
                    elif contador == 7:
                        linha["data_disponibilizacao"] = info.td.text.strip().split("\n\t")[-1].strip()
                    elif contador == 8:
                        linha["decisao"] = info.td.find_all('div', {'style': 'display: none;'})[-1].span.text.strip()

                    contador += 1

                dados.append(linha)  # Adiciona a linha aos dados

    # Retorna os dados como um DataFrame
    # pd.DataFrame(dados).to_excel(f"decisoes_tjsp_{date.today()}.xlsx", index=False)
    return pd.DataFrame(dados)



# Lista de links
# Execução

import pandas as pd

input_data = pd.read_excel('dados_sentencas.xlsx')
input_data.input2 = input_data.PROCESSO.str[-4:]
links = list()
df = pd.DataFrame()
for _,row in input_data.iterrows():
    link = f'https://esaj.tjsp.jus.br/cjpg/pesquisar.do;jsessionid=A3B093BF00038BA60208A3DFE512B566.cjpg1?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado={row.input1}&foroNumeroUnificado={row.input2}&dadosConsulta.nuProcesso={row.PROCESSO}&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=&varasTreeSelection.text=&dadosConsulta.ordenacao=DESC'
    links.append(link)
df = extract_decisoes_tjsp_grau1(links)
df.to_excel(f"decisoes_tjsp_{date.today()}.xlsx", index=False)