In [10]:
import pandas as pd

df = pd.read_csv('editais.csv')
df.head()
df.edital[1]

'\n\t\n                            \n    \n    \n    \n    \n\n            \n               \n            \n                \n    \n\t\n    \n\n    \n        \n\n    \n\n\n    \n        \n            \n                \n                    \n                        \n                            Sistema BEC/SP\n                    \n                        \n                            Bolsa Eletrônica de Compras do Governo do Estado de São Paulo\n                    \n                        \n                            EDITAL DE CONVITE ELETRÔNICO \n                                \n                                \n                    \n                        \n                            \xa0\n                    \n                        PREÂMBULO\n                    \n                        \n                            \xa0\n                    \n                        Edital CV nº \n                            080261000012014OC00052 referente à Oferta de Compra nº 080261000012014OC00052\n                    \n                        a) Unidade Compradora: UC: 080261 - DIR.ENS.REGIAO CENTRO CNPJ: 46384111003084\n                    \n                        ORGÃO/ ENTIDADE\n                            SECRETARIA DA EDUCACAO\n                            \n                            \n                    \n                        b) Procedimento: licitação na modalidade Convite, nos termos do art.\n                                22, inciso III e § 3º, da Lei federal nº 8.666, de 21 de junho de 1993 e art. 22,\n                                inciso III, da Lei estadual nº 6.544, de 22 de novembro de 1989.\n                                \n                                \n                    \n                        c) Tipo de licitação: menor preço\n                     \n                        d) Objeto:\n                                                  Qtde            Unidade de Fornecimento            Material (Clique no material               para visualizar a descrição completa do item)                     50PACOTE      200,00 GRAMA\n\t\t\tBISCOITO C/SAL                           \n     \n                        e) Propostas: em moeda corrente nacional, real (R$), com quatro casas\n                                depois da vírgula.\n                    \n                        f) Local de entrega: Unidade DIR.ENS.REGIAO CENTRO, localizada na Rua AV. OLAVO FONTOURA, Nº 2222,\n                                bairro CASA VERDE, Município de SAO PAULO, SP. \n                    \n                        g) Prazo de entrega: 0 dias a partir da celebração\n                                da contratação, conforme disciplinado no subitem 7.3.\n                                \n                                \n                    \n                        h) Prazo de pagamento: 30dias contados de\n                                acordo com o estabelecido nos subitens 10.1 e 10.2\n                    \n                        i) Regime de execução: entrega imediata, em parcela única.\n                    \n                        j) Recebimento/entrega das propostas: via Internet, no endereço eletrônico\n                            www.bec.sp.gov.br, até às 13:00:00 horas do dia 19/11/2014.\n                    \n                        k) Sessão pública de abertura e divulgação das propostas: imediatamente\n                                após o encerramento do período para recebimento/entrega, indicados na alínea "j".\n                                \n                                \n                    \n                        l) Fundamento legal: Lei federal nº 8.666/1993 e Lei estadual nº 6.544/1989;\n                                Decretos estaduais nºs 45.085/2000,\n                                    45.695/2001 e 61.363, de 08 de julho de 2015. Caso o objeto da licitação\n                                contemple a aquisição de medicamentos, correlatos, saneantes domissanitários\n                                e cosméticos de uso médico, odontológico ou hospitalar aplicam-se também: Leis federais\n                                n°s 6.360/1976 e 9.787/1999 e Lei estadual n° 10.083/1998\n                                - Código Sanitário do Estado; Decreto estadual n° 47.168/2002. \n                                        \n                                        \n                    \n                        m) Sanções Administrativas: artigos 81, 86 e 87 da Lei federal nº\n                                8.666/1993, artigos 79, 80 e 81 da Lei estadual nº 6.544/1989.\n                                \n                                \n                    \n                        \n                    \n                        \n                    \n                        \n                            \xa0\n                    \n                        1. Da Participação\n                    \n                        1.1. Poderão participar da licitação como convidados todos os fornecedores\n                                inscritos no Cadastro Unificado de Fornecedores do Estado de São Paulo - \n                                    Caufesp,\n                                    em atividade\n                                        econômica compatível com o objeto da licitação, que sejam detentores de senha para\n                                        participar de procedimentos eletrônicos, e que tenham credenciado os seus representantes,\n                                        na forma estabelecida no regulamento que disciplina a inscrição no referido Cadastro.\n                    \n                        1.2. Poderão, ainda, participar da licitação,\n                                os demais fornecedores não convidados que, preenchidas as condições estabelecidas\n                                no subitem 1.1, obtiverem inscrição no Caufesp e senha\n                                para participar de procedimentos eletrônicos, até 24 (vinte e quatro) horas antes\n                                do encerramento do prazo para recebimento/entrega das propostas, estabelecido na\n                                alínea "j", do preâmbulo deste Edital.\n                                \n                                \n                    \n                        1.3. A inscrição no Caufesp, o credenciamento\n                                dos representantes que atuarão em nome da licitante no sistema de convite eletrônico\n                                e a senha de acesso, deverão ser obtidos anteriormente à abertura da sessão pública\n                                de abertura e divulgação das propostas.\n                    \n                        1.4. As informações a respeito das condições exigidas e dos procedimentos\n                                a serem cumpridos para a inscrição no Caufesp, para\n                                o credenciamento de representantes e para a obtenção de senha de acesso, estão disponíveis\n                                no endereço eletrônico \n                                    www.bec.sp.gov.br.\n                    \n                        1.5. A participação no certame está condicionada, ainda, a que o interessado\n                                ao acessar inicialmente o ambiente eletrônico de contratações do Sistema BEC/SP,\n                                declare, mediante assinalação nos campos próprios, que inexiste qualquer fato impeditivo\n                                de sua participação no certame ou de sua contratação e que conhece e aceita o regulamento\n                                do convite eletrônico do Sistema BEC/SP, responsabilizando-se pela autenticidade\n                                e procedência dos bens que cotar.\n                                \n                                \n                    \n                        1.6. A licitante responde integralmente por todos os atos praticados\n                                no convite eletrônico, por seus representantes devidamente credenciados, assim como\n                                pela utilização da senha de acesso ao sistema, ainda que indevidamente, inclusive\n                                por pessoa não credenciada como sua representante.\n                    \n                        1.7. O envio de proposta vinculará a licitante ao cumprimento de todas\n                                as condições e obrigações inerentes à licitação e a contratação que dela poderá\n                                se originar.\n                    \n                        1.8. Para o exercício do direito de preferência de que trata o subitem\n                                3.5, deste Edital, a condição de microempresa, de empresa de pequeno porte, ou de\n                                cooperativa que preencha as condições estabelecidas no artigo 34, da Lei federal\n                                n° 11.488, de 15 de junho de 2007, deverá constar do registro da licitante junto\n                                ao Caufesp.\n                    \n                        \n                            \xa0\n                    \n                        2. Da Apresentação das Propostas\n                    \n                        2.1. As propostas deverão ser enviadas por meio eletrônico disponível\n                                no endereço indicado na alínea "j" do preâmbulo deste Edital, até o horário\n                                indicado na mesma alínea "j", permanecendo criptografadas pelo Sistema\n                                BEC/SP, até o momento de sua abertura e divulgação, mediante grade ordenatória em\n                                ordem crescente de preços, elaborada pelo referido sistema.\n                                \n                                \n                    \n                        2.2. A proposta deverá conter os seguintes elementos: a) a procedência,\n                                a marca e o modelo do produto cotado, por item, de acordo com as especificações\n                                contidas na alínea "d", do preâmbulo deste Edital; b) preço da unidade\n                                de fornecimento, por item, em moeda corrente nacional, apurado à data de sua apresentação,\n                                sem inclusão de qualquer encargo financeiro ou previsão inflacionária. No preço\n                                proposto deverão estar incluídos, além do lucro, todas as despesas e custos, como\n                                por exemplo: transportes, tributos de qualquer natureza e todas as despesas, diretas\n                                ou indiretas, relacionadas ao objeto da licitação.\n                    \n                        2.2.1. Se o objeto da licitação consistir em aquisição de medicamentos,\n                                ou de correlatos, ou de saneantes domissanitários ou\n                                de cosméticos de uso médico, odontológico ou hospitalar, além dos elementos mencionados\n                                no subitem 2.2, deste Edital, a proposta deverá conter a indicação: a) do fabricante\n                                e do tipo de embalagem e da quantidade de cada produto cotado, em cada embalagem;\n                                b) do tipo (genérico, de marca ou similar - no caso de medicamentos); e c) do número\n                                completo do registro do produto cotado, junto ao Ministério da Saúde/ANVISA, para\n                                diligência no endereço eletrônico da Agência Nacional de Vigilância Sanitária -\n                                ANVISA, com vistas à aferição de sua regularidade, ou, se o produto for isento desse\n                                registro, informação confirmando essa isenção.\n                    \n                        2.2.2. Se o objeto da licitação consistir em aquisição de medicamentos,\n                                os preços propostos deverão observar, ainda, as disposições legais e regulamentares\n                                aplicáveis à determinação dos preços dos medicamentos, especialmente os respectivos\n                                tetos, quando for o caso.\n                    \n                        2.3. O prazo de validade da proposta será de 60 (sessenta) dias contado\n                                da data de sua apresentação.\n                    \n                        2.4. Não serão admitidas cotações inferiores às quantidades previstas\n                                neste Edital.\n                    \n                        2.5. Se o objeto da licitação consistir em aquisição de medicamentos,\n                                ou de correlatos, ou de saneantes domissanitários ou\n                                de cosméticos de uso médico, odontológico ou hospitalar, a apresentação de proposta\n                                implica, obrigatoriamente, a assunção dos seguintes compromissos: a) as embalagens\n                                a serem entregues deverão conter quantidade idêntica ou submúltiplo da quantidade\n                                licitada; b) as embalagens a serem entregues deverão conter os seguintes dizeres:\n                                "Produto destinado a entidades públicas - PROIBIDA A VENDA PELO COMÉRCIO".\n                    \n                        2.6. O preço ofertado permanecerá fixo e irreajustável.\n                                \n                                \n                    \n                        \n                            \xa0\n                    \n                        3. Da Análise e do Julgamento das Propostas\n                    \n                        3.1. No dia e horário estabelecidos na alínea "k", do preâmbulo\n                                deste Edital, o Sistema BEC/SP, automaticamente, decodificará as propostas, tornando-as\n                                públicas, via Internet, para todos os interessados, no endereço eletrônico constante\n                                da alínea "j", na forma de grade ordenatória, em ordem crescente de preços\n                                ofertados. Essa grade conterá a identificação de todos os licitantes, bem como os\n                                preços ofertados, relativos a cada um dos itens.\n                    \n                        3.2. A análise das propostas levará em conta o atendimento de todas\n                                as condições estabelecidas neste convite, sendo desclassificada a proposta que:\n                                a) estiver em desacordo com qualquer das exigências estabelecidas no Edital; b)\n                                apresentar preço simbólico, irrisório ou de valor zero, incompatível com os preços\n                                dos insumos ou salários de mercado, ou que se revelar manifestamente inexequível,\n                                nos termos do artigo 48, inciso II, da Lei federal n° 8.666/1993; c) em se tratando\n                                de aquisição de medicamentos, não observar as disposições legais e regulamentares\n                                aplicáveis à determinação dos preços, especialmente os respectivos tetos, quando\n                                for o caso.\n                    \n                        3.2.1. \n                                    Se o objeto da licitação consistir em aquisição de medicamentos, ou de correlatos,\n                                    ou de saneantes domissanitários ou de cosméticos de\n                                    uso médico, odontológico ou hospitalar, adicionalmente ao previsto no subitem 3.2,\n                                    deste Edital, a proposta será desclassificada caso se constate que o registro do\n                                    produto na ANVISA não está em vigor, que o mesmo registro não corresponde ao produto\n                                    oferecido, ou que os elementos apresentados não permitam à verificação da regularidade\n                                    do referido produto.\n                                    \n                                    \n                    \n                        3.3. Não será considerada para fins de julgamento da proposta: a) oferta\n                                de vantagem não prevista neste Edital e nem preço ou vantagem baseada nas ofertas\n                                das demais licitantes; b) oferta de prazo ou condições diferentes dos fixados neste\n                                convite.\n                    \n                        3.4. O julgamento das propostas será efetuado pelo responsável pelo\n                                convite. Com base no julgamento o sistema elaborará a grade de classificação das\n                                propostas, observada a ordem crescente dos preços apresentados.\n                    \n                        3.4.1. A aceitabilidade dos preços ofertados será aferida no momento da\n                                análise das propostas, a partir dos preços de mercado vigentes na data de apresentação\n                                das mesmas propostas, nos termos da pesquisa de preços realizada pela Administração,\n                                observado o disposto no artigo 3° do Decreto n°.61.363/2015.\n                    \n                        3.4.1.1. Em se tratando de aquisição de medicamentos, a aceitabilidade dos\n                                preços levará em consideração, também, a observância das disposições legais e regulamentares\n                                aplicáveis à determinação dos preços, especialmente os respectivos tetos, quando\n                                for o caso.\n                    \n                        3.5. Com base na classificação de que trata o subitem 3.4, \n                                    será assegurada às licitantes microempresas, empresas de pequeno porte\n                                e às cooperativas que preencham as condições estabelecidas no artigo 34, da Lei\n                                federal n° 11.488/2007, preferência à contratação, observadas as seguintes regras:\n                    \n                        3.5.1. A microempresa, empresa de pequeno porte,\n                                        ou cooperativa, nos moldes indicados no subitem 3.5, detentora da proposta de menor\n                                        valor, dentre aquelas cujos valores sejam iguais ou superiores até 10% (dez por\n                                        cento) ao valor da proposta melhor classificada, será selecionada para que apresente\n                                        preço inferior ao da melhor classificada.\n                    \n                        3.5.2. A seleção recairá sobre a licitante vencedora de sorteio no caso\n                                de haver propostas empatadas nas condições do subitem 3.5.1.\n                    \n                        3.5.3. O exercício do direito de que trata o subitem 3.5.1 deverá ocorrer,\n                                sob pena de preclusão, no prazo de 1 (um) dia útil, contado\n                                da data de divulgação no próprio sistema do convite \n                                        eletrônico, da situação "exercício do direito de preferência", com a indicação\n                                        da licitante selecionada para esse exercício.\n                    \n                        3.5.3.1. Não havendo a apresentação de novo preço inferior ao da proposta\n                                melhor classificada, por parte da licitante selecionada nas condições do subitem\n                                3.5.1, as demais microempresas, empresas de pequeno porte e cooperativas, nos moldes\n                                indicados no subitem 3.5, cujos valores se enquadrem nas mesmas condições, poderão\n                                exercer o dir

In [8]:
df.decisao[0]

'SENTENÇA\r\n\r\nProcesso Digital nº:\t1014984-85.2025.8.26.0554\r\nClasse - Assunto\tProcedimento Comum Cível - Tratamento médico-hospitalar\r\nRequerente:\tAmil Assistencia Médica Internacional S/A\r\nRequerido:\tAntonio Vanderly Lima e outro\r\n\r\n\r\n\r\n\r\n\r\nJuiz(a) de Direito: Dr(a). Alberto Gentil de Almeida Pedroso\r\n\r\nVistos.\r\n\r\nAMIL ASSISTÊNCIA MÉDICA INTERNACIONAL S.A. ingressou com ação de nulidade contratual em face de ANTONIO VANDERLY LIMA E OUTRO, alegando, em síntese, que em 01 de agosto de 2024 o requerido aderiu a plano de saúde da autora por meio de proposta firmada em nome da pessoa jurídica demandada, sendo que na ocasião preencheu a declaração de saúde, afirmando que gozava de plena saúde, respondendo negativamente às perguntas relacionadas a doenças ou lesões preexistentes, firmando o documento ao final. Ocorre que poucos meses após a contratação do plano, o réu buscou pronto-atendimento e restou evidenciado que era portador de dislipidemia, asma e dor torácica, o que não foi declarado no ato da contratação, mesmo já possuindo conhecimento da preexistência das patologias, que se declaradas sujeitariam o requerido à cobertura parcial temporária. Sustenta que houve fraude, sendo legítima a recusa de cobertura exarada pela ré, pois violada a boa-fé objetiva pelo usuário. Pugna pela procedência da ação, a fim de que seja reconhecida a fraude perpetrada, com consequente autorização da abstenção de atendimentos, cancelamento do contrato ou, alternativamente, cumprimento do período de CPT, condenação do réu na restituição dos valores pagos a título de reembolso, inclusive no curso da ação. Juntou documentos (fls. 22/111). \r\n\r\nContestação a fls. 122/136, certificada sua intempestividade a fls. 211.\r\n\r\n\r\nÉ O RELATÓRIO.\r\n\r\nFUNDAMENTO E DECIDO.\r\n\r\n\t\tAnte a intempestividade da defesa apresentada e a suficiência da prova documental juntada aos autos, passo ao imediato julgamento do feito, nos termos do artigo 355, I e II do CPC. \r\n\r\n\t\tRessalto que a revelia, entretanto, não induz à procedência automática dos pedidos formulados, considerando que pode haver o convencimento em sentido contrário.\r\n\r\n\t\tNo mérito, o ponto controvertido central reside na caracterização ou não da doença como preexistente e na existência de má-fé por parte do beneficiário ao omitir tal condição. \r\n\r\n\t\tA autora sustenta que as doenças constantes do atendimento médico de fls.  94 (asma, dislipidemia e dor torácica) deveriam ter sido declaradas pelo requerido, ante a sua antecedência em relação ao preenchimento da declaração de saúde.\r\n\r\n\t\tA controvérsia, portanto, gira em torno da existência de má-fé, da caracterização da doença como preexistente e da legitimidade da negativa de cobertura.\r\n\r\n\t\tO contrato de plano de saúde é regido pela boa-fé objetiva, que impõe às partes o dever de agir com lealdade, transparência e cooperação.\r\n\r\n\t\tÉ fato que o beneficiário respondeu negativamente à pergunta sobre doenças preexistentes. Contudo, essa resposta não pode ser interpretada isoladamente. A ausência da prova de sintomas, de acompanhamento médico e de qualquer manifestação clínica das doenças à época da contratação afasta a presunção de má-fé. A jurisprudência do Superior Tribunal de Justiça é pacífica ao exigir prova inequívoca de dolo para que se configure omissão relevante. A resposta negativa, nesse contexto, reflete o entendimento legítimo do beneficiário de que não havia doença ativa ou relevante a declarar.\r\n\r\n\t\tA jurisprudência consolidada do STJ, por meio da Súmula 609, estabelece que: \r\n\r\n\t\t“A recusa de cobertura securitária, sob a alegação de doença preexistente,é ilícita se não houve a exigência de exames médicos prévios à contratação ou a demonstração de má-fé do segurado.”\r\n\r\n\t\tNo caso concreto, não houve exigência de exames médicos prévios nem prova inequívoca de má-fé. A ausência de prova inequívoca de sintomas ou diagnóstico ativo afasta a caracterização de omissão dolosa, sendo indevida a imposição de CPT ou a rescisão contratual.\r\n\r\n\t\tAplica-se ao contrato o Código de Defesa do Consumidor, conforme Súmula 608 do STJ, sendo abusiva a cláusula que permite rescisão unilateral com base em presunção de fraude não comprovada. A operadora, como fornecedora de serviço essencial, deve respeitar a função social do contrato, que é garantir o acesso à saúde.\r\n\r\n\t\tAdemais, a conduta contraditória da operadora, que aceita a contratação e somente após o surgimento da demanda médica alega fraude, configura violação à vedação do comportamento contraditório, derivada da boa-fé objetiva.\r\n\r\n\t\tAnte o exposto, JULGO IMPROCEDENTE o pedido formulado pela autora, nos termos do art. 487, I do Código de Processo Civil, resolvendo o mérito da ação.\r\n\t\tCondeno a autora ao pagamento das custas processuais e honorários advocatícios, que fixo em 10% sobre o valor da causa, nos termos do art. 85, §2º do CPC.\r\n\r\n\t\tArquivem-se os autos em momento oportuno, efetuando-se as comunicações necessárias.\r\n\r\n\t\tPIC\r\n\r\nSanto André, 08 de setembro de 2025.\r\n\r\n\r\nDOCUMENTO ASSINADO DIGITALMENTE NOS TERMOS DA LEI 11.419/2006, CONFORME IMPRESSÃO À MARGEM DIREITA'

In [3]:
import pandas as pd
import os

df = pd.DataFrame()
for arquivo in os.listdir('aula4'):
    if arquivo.endswith('.csv'):
        df = pd.concat([df, pd.read_csv(f'aula4/{arquivo}')], ignore_index=True)
df.head()

,numero_cnj,classe,assunto,magistrado,comarca,foro,vara,data_disponibilizacao,decisao
0,1014984-85.2025.8.26.0554,Procedimento Comum Cível,Tratamento médico-hospitalar,Alberto Gentil de Almeida Pedroso,Santo André,Foro de Santo André,8ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t1014984-...
1,1024257-39.2025.8.26.0053,Procedimento do Juizado Especial da Fazenda Pú...,Fornecimento de medicamentos,Alexandra Fuchs de Araujo,SÃO PAULO,Foro Central - Fazenda Pública/Acidentes,3ª Vara do Juizado Especial da Fazenda Pública...,08/09/2025,DECISÃO\r\n\r\nProcesso Digital nº:\t1024257-3...
2,0004884-06.2025.8.26.0161,Cumprimento Provisório de Sentença,Tratamento médico-hospitalar,RODRIGO SOUSA DAS GRACAS,Diadema,Foro de Diadema,3ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital:\t0004884-06....
3,0000017-17.2025.8.26.0210,Requisição de Pequeno Valor,Fornecimento de medicamentos,LUCAS DUCATTI MARQUEZ DE ANDRADE,Guaíra,Foro de Guaíra,1ª Vara,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t0000017-...
4,1016320-41.2024.8.26.0011,Procedimento Comum Cível,Tratamento médico-hospitalar,PAULO HENRIQUE RIBEIRO GARCIA,SÃO PAULO,Foro Regional XI - Pinheiros,1ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nCONCLUSÃO\r\nEm 05 de setembro...

In [7]:
import re

termos = {
    'requerente': r'(?<=requerente:)(.*)(?=requerido:)',
    'requerido': r'(?<=requerido:)(.*)(?=juiz\(a\))',
}

req_te = list()
req_do = list()

for _,row in df.iterrows():
    if type(row.decisao) == str:
        for u,v in termos.items():
            regex = re.search(v, row.decisao, re.I|re.S)
            if regex:
                if u == 'requerente':
                    req_te.append(regex.group().strip())
                elif u == 'requerido':
                    req_do.append(regex.group().strip())
            else:
                if u == 'requerente':
                    req_te.append(None)
                elif u == 'requerido':
                    req_do.append(None)
    else:
        req_te.append(None)
        req_do.append(None)
        
df['requerente'] = req_te
df['requerido'] = req_do
df.head()

,numero_cnj,classe,assunto,magistrado,comarca,foro,vara,data_disponibilizacao,decisao,requerente,requerido
0,1014984-85.2025.8.26.0554,Procedimento Comum Cível,Tratamento médico-hospitalar,Alberto Gentil de Almeida Pedroso,Santo André,Foro de Santo André,8ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t1014984-...,Amil Assistencia Médica Internacional S/A,Antonio Vanderly Lima e outro
1,1024257-39.2025.8.26.0053,Procedimento do Juizado Especial da Fazenda Pú...,Fornecimento de medicamentos,Alexandra Fuchs de Araujo,SÃO PAULO,Foro Central - Fazenda Pública/Acidentes,3ª Vara do Juizado Especial da Fazenda Pública...,08/09/2025,DECISÃO\r\n\r\nProcesso Digital nº:\t1024257-3...,Juliana Ferreira de Oliveira,None
2,0004884-06.2025.8.26.0161,Cumprimento Provisório de Sentença,Tratamento médico-hospitalar,RODRIGO SOUSA DAS GRACAS,Diadema,Foro de Diadema,3ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital:\t0004884-06....,Lucas Homero da Silva,None
3,0000017-17.2025.8.26.0210,Requisição de Pequeno Valor,Fornecimento de medicamentos,LUCAS DUCATTI MARQUEZ DE ANDRADE,Guaíra,Foro de Guaíra,1ª Vara,08/09/2025,SENTENÇA\r\n\r\nProcesso Digital nº:\t0000017-...,None,None
4,1016320-41.2024.8.26.0011,Procedimento Comum Cível,Tratamento médico-hospitalar,PAULO HENRIQUE RIBEIRO GARCIA,SÃO PAULO,Foro Regional XI - Pinheiros,1ª Vara Cível,08/09/2025,SENTENÇA\r\n\r\nCONCLUSÃO\r\nEm 05 de setembro...,Priscilla Lupiani Augusto Pereira,NOTRE DAME INTERMEDICA SAUDE S.A.

In [ ]:
import json
import pandas as pd
import os

df = pd.DataFrame()
for arquivo in os.listdir('dados_exemplo'):
    if not arquivo.endswith('edital.txt'):
        with open(f'dados_exemplo/{arquivo}', 'r+') as f:
            data = json.load(f)
        try:
            df = pd.concat([df, pd.json_normalize(data, max_level=1)], ignore_index=True)
        except:
            pass
df.head()
df.to_csv('compras_publicas.csv', index=False)

,OC,MUNICIPIO,UF,DT_INICIO,DT_FIM,QTD_ITENS,UNIDADE_COMPRADORA,MODALIDADE,LINK_EDITAL,ITENS,...,DESC_ATA_GERADACV_ABERTURA.CONVITE_DESISTENCIAS,DESC_ATA_GERADACV_ABERTURA.RESPONSAVEL,DESC_ATA_GERADACV_ENCERRAMENTO.ANALISE_PROPOSTAS,DESC_ATA_GERADACV_ENCERRAMENTO.CONVITE_SORTEIO,DESC_ATA_GERADACV_ENCERRAMENTO.DIREITO_PREFERENCIA,DESC_ATA_GERADACV_ENCERRAMENTO.CLASSIFICACAO_FINAL_PROPOSTAS,DESC_ATA_GERADACV_ENCERRAMENTO.ITENS_DESERTOS_FRACASSADOS,DESC_ATA_GERADACV_ENCERRAMENTO.RESPONSAVEIS,DESC_ATA_GERADACV_ENCERRAMENTO.FORNECEDORES_VENCEDORES,DESC_ATA_GERADACV_ENCERRAMENTO.DT_ENCERRAMENTO
0,080259000012012OC00009,SãO PAULO - SP,SP,27/06/2012 12:38:00,05/07/2012 14:56:00,24,COORDENADORIA DE GESTAO DE RECURSOS HUMANOS,Convite Eletrônico,https://www.bec.sp.gov.br/BEC_Convite_UI/ui/BE...,"[{'NR_SEQUENCIA_ITEM': '1', 'CD_ITEM': '374752...",...,[],None,[],[],None,None,None,None,None,None
1,080261000012014OC00052,SAO PAULO,SP,11/11/2014 11:23:00,19/11/2014 13:00:00,17,DIR.ENS.-REG.CENTRO,Convite Eletrônico,https://www.bec.sp.gov.br/BEC_Convite_UI/ui/BE...,"[{'NR_SEQUENCIA_ITEM': '1', 'CD_ITEM': '98329'...",...,[],None,[],[],None,None,None,None,None,None
2,080261000012019OC00009,SãO PAULO,SP,16/05/2019 10:49:07,24/05/2019 14:10:00,1,DIR.ENS.-REG.CENTRO,Convite Eletrônico,https://www.bec.sp.gov.br/BEC_Convite_UI/ui/BE...,"[{'NR_SEQUENCIA_ITEM': '1', 'CD_ITEM': '519745...",...,[],"{'NOME_RESPONSAVEL': 'Maria Cristina Mazzi', '...","[{'NR_SEQ_ITEM': '1', 'CNPJ': '68925593000130'...",[],[],"[{'NR_SEQ_ITEM': '1', 'CNPJ': '68925593000130'...",[],"[{'NOME_RESPONSAVEL': 'Maria Cristina Mazzi', ...","[{'NR_SEQ_ITEM': '1', 'CNPJ': '68925593000130'...",27/05/2019 11:42:38
3,080262000012009OC00063,SãO PAULO,SP,18/08/2009 09:27:00,26/08/2009 09:32:00,57,DIR.ENS.-REG.CENTRO OESTE,Convite Eletrônico,https://www.bec.sp.gov.br/BEC_Convite_UI/ui/BE...,"[{'NR_SEQUENCIA_ITEM': '1', 'CD_ITEM': '250994...",...,[],None,[],[],None,None,None,None,None,None
4,080262000012010OC00027,SãO PAULO,SP,02/07/2010 14:38:00,13/07/2010 10:00:00,3,DIR.ENS.-REG.CENTRO OESTE,Convite Eletrônico,https://www.bec.sp.gov.br/BEC_Convite_UI/ui/BE...,"[{'NR_SEQUENCIA_ITEM': '1', 'CD_ITEM': '150888...",...,[],None,[],[],None,None,None,None,None,None

In [ ]:
import json
import pandas as pd
import os

df = pd.DataFrame()
texto = list()
processo = list()
for arquivo in os.listdir('dados_exemplo'):
    if arquivo.endswith('edital.txt'):
        with open(f'dados_exemplo/{arquivo}', 'r+') as f:
            data = f.read()
        texto.append(data)
        processo.append(arquivo.split('_')[0])

df['edital'] = texto
df['processo'] = processo
df.head()
df.to_csv('editais.csv', index=False)

                                              edital                processo
0  \n\t\n                            \n    \n    ...  080259000012012OC00009
1  \n\t\n                            \n    \n    ...  080261000012014OC00052
2  \n\t\n                            \n    \n    ...  080261000012019OC00009
3  \n\t\n                            \n    \n    ...  080262000012009OC00063
4  \n\t\n                            \n    \n    ...  080262000012010OC00027

In [10]:
import re
import pandas as pd

df = pd.read_csv('editais.csv')
df.head()

termos = {
    'administrativo': r'administ',
    'judicial': r'judicial|juridico|justi[çc]a'
}

adm = list()
jud = list()

for _,row in df.iterrows():
    for u,v in termos.items():
        regex = re.search(v, row.edital, re.I|re.S)
        if regex:
            if u == 'administrativo':
                adm.append(row.edital[regex.span()[0]-20:regex.span()[1]+20])
            elif u == 'judicial':
                jud.append(row.edital[regex.span()[0]-20:regex.span()[1]+20])
        else:
            if u == 'administrativo':
                adm.append(None)
            elif u == 'judicial':
                jud.append(None)

df['administrativo'] = adm
df['judicial'] = jud
df.head()

,edital,processo,administrativo,judicial
0,\n\t\n \n \n ...,080259000012012OC00009,"m) Sanções Administrativas: artigos 81,",None
1,\n\t\n \n \n ...,080261000012014OC00052,"m) Sanções Administrativas: artigos 81,",None
2,\n\t\n \n \n ...,080261000012019OC00009,"m) Sanções Administrativas: artigos 81,",None
3,\n\t\n \n \n ...,080262000012009OC00063,"m) Sanções Administrativas: artigos 81,",None
4,\n\t\n \n \n ...,080262000012010OC00027,"m) Sanções Administrativas: artigos 81,",None

In [11]:
df.judicial.unique()

array([None, 'de FRANCA/SP - AÇÃO JUDICIAL, SP.  \n            ',
       ' ATRAVES DE DEMANDA JUDICIAL.\n                  ',
       'ROCABA, SP. DEMANDA JUDICIAL | LOCAL DE ENTREGA:',
       '             SEC.DA JUSTICA E CIDADANIA\n       '], dtype=object)